--CONFIGURACIONES EXTRAS

--ASIGNACION AL TBS
ALTER USER ADMINISTRATOR DEFAULT TABLESPACE FIDE_LOS_JAULES_TBS;

--SE CORRE EN SYS O DEBO DARLE DBA AL ROL DE ADMIN???
CREATE ROLE FIDE_LOS_JAULES_CLIENTE_ROLE;
--GRANTS PARA EL ROLE DE CLIENTE

GRANT SELECT ON ADMINISTRATOR.FIDE_ASOCIADO_TB TO FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_BENEFICIOS_MEMBRESIAS_TB TO FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_BENEFICIOS_TB TO FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_CANTONES_TB TO FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_CARGO_TB TO FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_CARRITO_ITEMS_TB TO FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_CARRITO_TB TO FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_CLAVE_ENCRIPTAR_TB TO FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_DIRECCIONES_TB TO FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_DISTRITOS_TB TO FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_EMAIL_TB TO FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_ESTADO_TB TO FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_EVENTOS_TB TO FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_FACTURA_TB TO FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_INVENTARIO_TB TO FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_INSTALACIONES_TB TO FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_INVITADOS_TB TO FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_MEMBRESIAS_TB TO FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_METODO_PAGO_TB TO FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_ORDEN_ITEMS_TB TO FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_ORDENES_TB TO FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_PRODUCTOS_PROVEEDOR_TB TO FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_PRODUCTOS_TB TO FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_PROVEEDORES_TB TO FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_PROVINCIAS_TB TO FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_REGISTRO_EVENTOS_TB TO FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_RESERVAS_TB TO FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_ROLES_TB TO FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_SERVICIOS_PROVEEDOR_TB TO FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_SERVICIOS_TB TO FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_TELEFONOS_TB TO FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_TIPO_INSTALACION_TB TO FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_TIPO_MEMBRESIAS_TB TO FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_USUARIOS_TB TO FIDE_LOS_JAULES_CLIENTE_ROLE;


------------------------------------------------------------------------



--AUDITORIA CORRIDO EN SYS
AUDIT ALL BY ADMINISTRATOR BY ACCESS; 
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_ASOCIADO_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_BENEFICIOS_MEMBRESIAS_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_CANTONES_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_CARGO_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_CARRITO_ITEMS_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_CARRITO_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_CLAVE_ENCRIPTAR_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_DIRECCIONES_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_DISTRITOS_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_EMAIL_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_ESTADO_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_EVENTOS_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_FACTURA_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_INSTALACIONES_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_INVENTARIO_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_INVITADOS_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_MEMBRESIAS_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_METODO_PAGO_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_ORDEN_ITEMS_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_ORDENES_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_PRODUCTOS_PROVEEDOR_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_PRODUCTOS_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_PROVEEDORES_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_PROVINCIAS_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_REGISTRO_EVENTOS_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_RESERVAS_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_ROLES_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_SERVICIOS_PROVEEDOR_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_SERVICIOS_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_TELEFONOS_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_TIPO_INSTALACION_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_TIPO_MEMBRESIAS_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_USUARIOS_TB BY ACCESS;

--LA IDEA ES CREAR VISTAS QUE UNIFIQUEN LA INFORMACION Y DARLE ACCESO AL CLIENTE A ESAS VISTAS, NO A LAS TABLAS
--SELEC SOBRE TABLAS
CREATE OR REPLACE VIEW FIDE_REGISTROS_EVENTOS_VIEW AS 
SELECT 


--AUDITORIA
DELETE FIDE_ESTADO_TB WHERE ID_ESTADO = 7

--PKS COMPUESTAS

ALTER TABLE ADMINISTRATOR.FIDE_ORDEN_ITEMS_TB
DROP CONSTRAINT FIDE_ORDEN_ITEMS_TB_ID_ORDEN_FK;

ALTER TABLE FIDE_ORDEN_ITEMS_TB
ADD CONSTRAINT FIDE_ORDEN_ITEMS_TB_ID_ORDEN_PK PRIMARY KEY (ID_ORDEN, ID_ORDEN_ITEM);

ALTER TABLE ADMINISTRATOR.FIDE_ORDEN_ITEMS_TB
DROP CONSTRAINT FIDE_ORDEN_ITEMS_TB_ID_ORDEN_ITEM_PK

ALTER TABLE ADMINISTRATOR.FIDE_ORDEN_ITEMS_TB
ADD CONSTRAINT FIDE_ORDEN_ITEMS_TB_ID_ORDEN_FK
FOREIGN KEY (ID_ORDEN)
REFERENCES ADMINISTRATOR.FIDE_ORDENES_TB(ID_ORDEN);

ALTER TABLE FIDE_CARRITO_ITEMS_TB
ADD CONSTRAINT FIDE_CARRITO_ITEMS_TB_ID_ITEM_CARRITO_PK PRIMARY KEY (ID_ITEM, ID_CARRITO);

COMMIT
--PARTICION

ALTER TABLE FIDE_FACTURA_TB
MODIFY PARTITION BY RANGE (FECHA_EMISION) (
    PARTITION P_2021 VALUES LESS THAN (TO_DATE('2022-01-01', 'YYYY-MM-DD')),
    PARTITION P_2022 VALUES LESS THAN (TO_DATE('2023-01-01', 'YYYY-MM-DD')),
    PARTITION P_2023 VALUES LESS THAN (TO_DATE('2024-01-01', 'YYYY-MM-DD')),
    PARTITION P_2024 VALUES LESS THAN (TO_DATE('2025-01-01', 'YYYY-MM-DD')),
    PARTITION P_2025 VALUES LESS THAN (TO_DATE('2026-01-01', 'YYYY-MM-DD'))
);


ALTER TABLE FIDE_EVENTOS_TB
MODIFY PARTITION BY RANGE (FECHA) (
    PARTITION P_2021 VALUES LESS THAN (TO_DATE('2022-01-01', 'YYYY-MM-DD')),
    PARTITION P_2022 VALUES LESS THAN (TO_DATE('2023-01-01', 'YYYY-MM-DD')),
    PARTITION P_2023 VALUES LESS THAN (TO_DATE('2024-01-01', 'YYYY-MM-DD')),
    PARTITION P_2024 VALUES LESS THAN (TO_DATE('2025-01-01', 'YYYY-MM-DD')),
    PARTITION P_2025 VALUES LESS THAN (TO_DATE('2026-01-01', 'YYYY-MM-DD'))
);


--MODIFICACION DE CONSTRAINTS - RENOMBRARLOS BIEN
--TABLA ASOCIADOS
ALTER TABLE FIDE_ASOCIADO_TB RENAME CONSTRAINT SYS_C007965 TO FIDE_ASOCIADO_TB_DESCRIPCION_CHECK;
ALTER TABLE FIDE_ASOCIADO_TB RENAME CONSTRAINT SYS_C007966 TO FIDE_ASOCIADO_TB_ESTADO_CHECK;
--TABLA BENEFICIOS MEMBRESIAS 
ALTER TABLE FIDE_BENEFICIOS_MEMBRESIAS_TB RENAME CONSTRAINT SYS_C008110 TO FIDE_BENEFICIOS_MEMBRESIAS_TB_TIPOMEMB_CHECK;
ALTER TABLE FIDE_BENEFICIOS_MEMBRESIAS_TB RENAME CONSTRAINT SYS_C008111 TO FIDE_BENEFICIOS_MEMBRESIAS_TB_BENEFICIO_CHECK;
ALTER TABLE FIDE_BENEFICIOS_MEMBRESIAS_TB RENAME CONSTRAINT SYS_C008112 TO FIDE_BENEFICIOS_MEMBRESIAS_TB_ESTADO_CHECK;

--TABLA BENEFICIOS
ALTER TABLE FIDE_BENEFICIOS_TB RENAME CONSTRAINT SYS_C008102 TO FIDE_BENEFICIOS_TB_ESTADO_CHECK;

--TABLA CANTONES
ALTER TABLE FIDE_CANTONES_TB RENAME CONSTRAINT SYS_C008008 TO FIDE_CANTONES_TB_NOMBRE_CHECK;
ALTER TABLE FIDE_CANTONES_TB RENAME CONSTRAINT SYS_C008009 TO FIDE_CANTONES_TB_PROVINCIA_CHECK;

--TABLA CARGO

ALTER TABLE FIDE_CARGO_TB RENAME CONSTRAINT SYS_C007961 TO FIDE_CARGO_TB_DESCRIPCION_CHECK;
ALTER TABLE FIDE_CARGO_TB RENAME CONSTRAINT SYS_C007962 TO FIDE_CARGO_TB_ESTADO_CHECK;

--TABLA CARRITO ITEMS
ALTER TABLE FIDE_DIRECCIONES_TB RENAME CONSTRAINT SYS_C008042 TO FIDE_DIRECCIONES_TB_DIRECCION_CHECK;
ALTER TABLE FIDE_DIRECCIONES_TB RENAME CONSTRAINT SYS_C008043 TO FIDE_DIRECCIONES_TB_DISTRITO_CHECK;

--TABLA DISTRITOS
ALTER TABLE FIDE_DISTRITOS_TB RENAME CONSTRAINT SYS_C008038 TO FIDE_DISTRITOS_TB_NOMBRE_CHECK;
ALTER TABLE FIDE_DISTRITOS_TB RENAME CONSTRAINT SYS_C008039 TO FIDE_DISTRITOS_TB_CANTON_CHECK;

--TABLA EMAIL
ALTER TABLE FIDE_EMAIL_TB RENAME CONSTRAINT SYS_C008000 TO FIDE_EMAIL_TB_EMAIL_CHECK;

--TABLA ESTADO
ALTER TABLE FIDE_ESTADO_TB RENAME CONSTRAINT SYS_C007959 TO FIDE_ESTADO_TB_DESCRIPCION_CHECK;

--TABLA EVENTOS
ALTER TABLE FIDE_EVENTOS_TB RENAME CONSTRAINT SYS_C008083 TO FIDE_EVENTOS_TB_NOMBRE_CHECK;
ALTER TABLE FIDE_EVENTOS_TB RENAME CONSTRAINT SYS_C008084 TO FIDE_EVENTOS_TB_DESCCRIPCION_CHECK;
ALTER TABLE FIDE_EVENTOS_TB RENAME CONSTRAINT SYS_C008085 TO FIDE_EVENTOS_TB_HORA_CHECK;
ALTER TABLE FIDE_EVENTOS_TB RENAME CONSTRAINT SYS_C008086 TO FIDE_EVENTOS_TB_FECHA_CHECK;
ALTER TABLE FIDE_EVENTOS_TB RENAME CONSTRAINT SYS_C008087 TO FIDE_EVENTOS_TB_ESTADO_CHECK;
ALTER TABLE FIDE_EVENTOS_TB RENAME CONSTRAINT SYS_C008088 TO FIDE_EVENTOS_TB_CAPACIDAD_CHECK;

--TABLA INVENTARIO
ALTER TABLE FIDE_INVENTARIO_TB RENAME CONSTRAINT SYS_C008057 TO FIDE_INVENTARIO_TB_CANTIDAD_CHECK;


--TABLA INVITADOS
ALTER TABLE FIDE_INVITADOS_TB RENAME CONSTRAINT SYS_C007990 TO FIDE_INVENTARIO_TB_CEDULA_CHECK;
ALTER TABLE FIDE_INVITADOS_TB RENAME CONSTRAINT SYS_C007991 TO FIDE_INVENTARIO_TB_FECHA_CHECK;
ALTER TABLE FIDE_INVITADOS_TB RENAME CONSTRAINT SYS_C007992 TO FIDE_INVENTARIO_TB_ESTADO_CHECK;
ALTER TABLE FIDE_INVITADOS_TB RENAME CONSTRAINT SYS_C007993 TO FIDE_INVENTARIO_TB_MIEMBRO_CHECK;

--TABLA MEMBRESIAS
ALTER TABLE FIDE_MEMBRESIAS_TB RENAME CONSTRAINT SYS_C008161 TO FIDE_MEMBRESIAS_TB_CEDULA_CHECK;
ALTER TABLE FIDE_MEMBRESIAS_TB RENAME CONSTRAINT SYS_C008162 TO FIDE_MEMBRESIAS_TB_FECHA_CHECK;
ALTER TABLE FIDE_MEMBRESIAS_TB RENAME CONSTRAINT SYS_C008163 TO FIDE_MEMBRESIAS_TB_ESTADO_CHECK;
ALTER TABLE FIDE_MEMBRESIAS_TB RENAME CONSTRAINT SYS_C008164 TO FIDE_MEMBRESIAS_TB_TIPO_MEMBRESIA_CHECK;

--TABLA PRODUCTOS PROVEEDOR
ALTER TABLE FIDE_PRODUCTOS_PROVEEDOR_TB RENAME CONSTRAINT SYS_C008050 TO FIDE_PRODUCTOS_PROVEEDOR_TB_PROVEEDOR_CHECK;
ALTER TABLE FIDE_PRODUCTOS_PROVEEDOR_TB RENAME CONSTRAINT SYS_C008051 TO FIDE_PRODUCTOS_PROVEEDOR_TB_PRODUCTO_CHECK;
ALTER TABLE FIDE_PRODUCTOS_PROVEEDOR_TB RENAME CONSTRAINT SYS_C008052 TO FIDE_PRODUCTOS_PROVEEDOR_TB_ESTADO_CHECK;

--TABLA PROVEEDORES
ALTER TABLE FIDE_PROVEEDORES_TB RENAME CONSTRAINT SYS_C008027 TO FIDE_PROVEEDORES_TB_ESTADO_CHECK;
ALTER TABLE FIDE_PROVEEDORES_TB RENAME CONSTRAINT SYS_C008028 TO FIDE_PROVEEDORES_TB_NOMBRE_CHECK;
ALTER TABLE FIDE_PROVEEDORES_TB RENAME CONSTRAINT SYS_C008029 TO FIDE_PROVEEDORES_TB_TELEFONO_CHECK;
ALTER TABLE FIDE_PROVEEDORES_TB RENAME CONSTRAINT SYS_C008031 TO FIDE_PROVEEDORES_TB_EMAIL_UNIQUE;

--TABLA PROVINCIAAS

ALTER TABLE FIDE_PROVINCIAS_TB RENAME CONSTRAINT SYS_C008006 TO FIDE_PROVINCIAS_TB_NOMBRE_CHECK;

--TABLA ROLES
ALTER TABLE FIDE_ROLES_TB RENAME CONSTRAINT SYS_C007969 TO FIDE_ROLES_TB_DESCRIPCION_CHECK;
ALTER TABLE FIDE_ROLES_TB RENAME CONSTRAINT SYS_C007970 TO FIDE_ROLES_TB_ESTADO_CHECK;

--TABLA SERVICIOS PROVEEDORES
ALTER TABLE FIDE_SERVICIOS_PROVEEDOR_TB RENAME CONSTRAINT SYS_C008063 TO FIDE_SERVICIOS_PROVEEDOR_TB_PROVEEDOR_CHECK;
ALTER TABLE FIDE_SERVICIOS_PROVEEDOR_TB RENAME CONSTRAINT SYS_C008064 TO FIDE_SERVICIOS_PROVEEDOR_TB_SERVICIO_CHECK;
ALTER TABLE FIDE_SERVICIOS_PROVEEDOR_TB RENAME CONSTRAINT SYS_C008065 TO FIDE_SERVICIOS_PROVEEDOR_TB_ESTADO_CHECK;

--TABLA SERVICIOS
ALTER TABLE FIDE_SERVICIOS_TB RENAME CONSTRAINT SYS_C008060 TO FIDE_SERVICIOS_TB_ESTADO_CHECK;

--TABLA TELEFONOS
ALTER TABLE FIDE_TELEFONOS_TB RENAME CONSTRAINT SYS_C007985 TO FIDE_TELEFONOS_TB_CEDULA_CHECK;
ALTER TABLE FIDE_TELEFONOS_TB RENAME CONSTRAINT SYS_C007986 TO FIDE_TELEFONOS_TB_ESTADO_CHECK;

--TABLA TIPO MEMBRESIAS
ALTER TABLE FIDE_TIPO_MEMBRESIAS_TB RENAME CONSTRAINT SYS_C008105 TO FIDE_TIPO_MEMBRESIAS_TB_DURACION_DIAS_CHECK;
ALTER TABLE FIDE_TIPO_MEMBRESIAS_TB RENAME CONSTRAINT SYS_C008106 TO FIDE_TIPO_MEMBRESIAS_TB_DESCRIPCION_CHECK;
ALTER TABLE FIDE_TIPO_MEMBRESIAS_TB RENAME CONSTRAINT SYS_C008107 TO FIDE_TIPO_MEMBRESIAS_TB_NOMBRE_CHECK;

--TABLA USUARIOS
ALTER TABLE FIDE_USUARIOS_TB RENAME CONSTRAINT SYS_C007973 TO FIDE_USUARIOS_TB_FECHA_INGRESO_CHECK;
ALTER TABLE FIDE_USUARIOS_TB RENAME CONSTRAINT SYS_C007974 TO FIDE_USUARIOS_TB_CONTRASENA_CHECK;
ALTER TABLE FIDE_USUARIOS_TB RENAME CONSTRAINT SYS_C007975 TO FIDE_USUARIOS_TB_NOMBRE_CHECK;
ALTER TABLE FIDE_USUARIOS_TB RENAME CONSTRAINT SYS_C007976 TO FIDE_USUARIOS_TB_APELLIDO1_CHECK;
ALTER TABLE FIDE_USUARIOS_TB RENAME CONSTRAINT SYS_C007977 TO FIDE_USUARIOS_TB_ROL_CHECK;
ALTER TABLE FIDE_USUARIOS_TB RENAME CONSTRAINT SYS_C007978 TO FIDE_USUARIOS_TB_ASOCIADO_CHECK;
ALTER TABLE FIDE_USUARIOS_TB RENAME CONSTRAINT SYS_C007979 TO FIDE_USUARIOS_TB_ESTADO_CHECK;

--TABLA CARRITO
ALTER TABLE FIDE_CARRITO_ITEMS_TB RENAME CONSTRAINT SYS_C008353 TO FIDE_CARRITO_ITEMS_TB_ID_CARRITO_CHECK;
COMMIT;

--CAMBIO EN LA TABLA ASOCIADO
ALTER TABLE FIDE_ASOCIADO_TB ADD CEDULA NUMBER
ALTER TABLE FIDE_USUARIOS_TB DROP COLUMN ID_ASOCIADO


---INSERTS EN TABLA ASOCIADO
CREATE SEQUENCE ID_ASOCIADO_SEQ INCREMENT BY 1 START WITH 1
MAXVALUE 999999 MINVALUE 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER FIDE_ASOCIADO_INSERT_TG
BEFORE INSERT ON FIDE_ASOCIADO_TB
FOR EACH ROW
BEGIN
        SELECT ID_ASOCIADO_SEQ.NEXTVAL INTO :NEW.ID_ASOCIADO FROM DUAL;
END;


ALTER TABLE FIDE_ASOCIADO_TB ADD CONSTRAINT FIDE_ASOCIADO_TB_CEDULA_UNIQUE UNIQUE (CEDULA);
ALTER TABLE FIDE_ASOCIADO_TB DROP CONSTRAINT FIDE_ASOCIADO_TB_ID_ASOCIADO_PK
ALTER TABLE FIDE_ASOCIADO_TB ADD CONSTRAINT FIDE_ASOCIADO_TB_ID_ASOCIADO_CEDULA_PK PRIMARY KEY (ID_ASOCIADO, CEDULA)


COMMIT;