--INSERTS
INSERT INTO FIDE_ESTADO_TB (ID_ESTADO, DESCRIPCION) VALUES (1, 'ACTIVO');
INSERT INTO FIDE_ASOCIADO_TB (ID_ASOCIADO, DESCRIPCION, ID_ESTADO) VALUES (1, 'PERSONA ASOCIADA', 1);
INSERT INTO FIDE_TIPO_MEMBRESIAS_TB (ID_TIPO_MEMBRESIA, COSTO, NOMBRE, DURACION_DIAS, NUM_INVITADOS, ID_ESTADO, DESCRIPCION)
VALUES (1, 20000.0, 'MEMBERESIA JAULES BÁSICA', 365, 1, 1, 'MEMBRESÍA BÁSICA, CON ACCESO LIMITADO A NUESTRAS INSTALACIONES'); 
COMMIT;

--INSERTS EN BENEFICIOS
INSERT INTO FIDE_BENEFICIOS_TB (ID_BENEFICIO, DESCRIPCION, ID_ESTADO) VALUES (1, 'Acceso al club', 1);
INSERT INTO FIDE_BENEFICIOS_TB (ID_BENEFICIO, DESCRIPCION, ID_ESTADO) VALUES (2, 'Gimnasio', 1);
INSERT INTO FIDE_BENEFICIOS_TB (ID_BENEFICIO, DESCRIPCION, ID_ESTADO) VALUES (3, 'Áreas deportivas', 1);
INSERT INTO FIDE_BENEFICIOS_TB (ID_BENEFICIO, DESCRIPCION, ID_ESTADO) VALUES (4, 'Facilidades de alojamiento', 1);
INSERT INTO FIDE_BENEFICIOS_TB (ID_BENEFICIO, DESCRIPCION, ID_ESTADO) VALUES (5, 'Facilidades para eventos', 1);
INSERT INTO FIDE_BENEFICIOS_TB (ID_BENEFICIO, DESCRIPCION, ID_ESTADO) VALUES (6, 'Acceso a piscina', 1);

--INSERTS EN BENEFICIOS MEMBRESIAS
INSERT INTO FIDE_BENEFICIOS_MEMBRESIAS_TB (ID_BENEFICIO_MEMBRESIAS, ID_TIPO_MEMB, ID_BENEFICIO, ID_ESTADO) VALUES (1, 1, 1, 1);
INSERT INTO FIDE_BENEFICIOS_MEMBRESIAS_TB (ID_BENEFICIO_MEMBRESIAS, ID_TIPO_MEMB, ID_BENEFICIO, ID_ESTADO) VALUES (2, 1, 6, 1);
COMMIT;

INSERT INTO FIDE_TIPO_INSTALACION_TB (ID_TIPO_INSTALACION, DESCRIPCION, ID_ESTADO) VALUES (1, 'Área Recreativa', 1);
INSERT INTO FIDE_TIPO_INSTALACION_TB (ID_TIPO_INSTALACION, DESCRIPCION, ID_ESTADO) VALUES (2, 'Cabañas', 1);
INSERT INTO FIDE_TIPO_INSTALACION_TB (ID_TIPO_INSTALACION, DESCRIPCION, ID_ESTADO) VALUES (3, 'Ranchos', 1);
INSERT INTO FIDE_TIPO_INSTALACION_TB (ID_TIPO_INSTALACION, DESCRIPCION, ID_ESTADO) VALUES (4, 'Salones', 1);
INSERT INTO FIDE_TIPO_INSTALACION_TB (ID_TIPO_INSTALACION, DESCRIPCION, ID_ESTADO) VALUES (5, 'Ejercicio', 1);
INSERT INTO FIDE_TIPO_INSTALACION_TB (ID_TIPO_INSTALACION, DESCRIPCION, ID_ESTADO) VALUES (6, 'Gastronomía', 1);

INSERT INTO FIDE_INSTALACIONES_TB VALUES (1, 'Área Abierta Los Jaúles', 0, 1, 100, 1);
INSERT INTO FIDE_INSTALACIONES_TB VALUES (2, 'Cabañas Los Jaúles', 21000, 2, 2, 1);
INSERT INTO FIDE_INSTALACIONES_TB VALUES (3, 'Habitación Los Jaúles', 11000, 1, 2, 1);
INSERT INTO FIDE_INSTALACIONES_TB VALUES (4, 'Cabaña Los Sueños', 25000, 2, 4, 1);

INSERT INTO FIDE_EVENTOS_TB VALUES (1, 'Zumba Class', 'Diviertete con nuestra clase de zumba', TO_TIMESTAMP('14:30', 'HH24:MI'), TO_DATE('30/03/2025', 'DD/MM/YYYY'), 1, 1, 100);

SELECT U.CEDULA, U.NOMBRE || ' ' || U.APELLIDO1 AS NOMBRE, I.ID_INVITADO, I.CEDULA AS CEDULA_INVITADO, I.ID_ESTADO
FROM FIDE_INVITADOS_TB I
INNER JOIN FIDE_USUARIOS_TB U
ON I.CEDULA_MIEMBRO = U.CEDULA;

SELECT * FROM FIDE_ROLES_TB
INSERT INTO FIDE_ROLES_TB VALUES (1, 'CLIENTE', 1);
INSERT INTO FIDE_USUARIOS_TB VALUES (118810955, TO_DATE('22/03/2025', 'DD/MM/YYYY'), NULL, '123456', 'Ariana', 'Fallas', 'Calderón', 1, 1, 1, NULL);
INSERT INTO FIDE_EMAIL_TB VALUES (1,118810955, 'arianafallas1@gmail.com');
INSERT INTO FIDE_RESERVAS_TB VALUES (1, 118810955, TO_DATE('22/03/2025', 'DD/MM/YYYY'), TO_DATE('24/03/2025', 'DD/MM/YYYY'), TO_TIMESTAMP('12:00', 'HH24:MI'),TO_TIMESTAMP('15:00', 'HH24:MI'), 2, 1, 2);
select * from fide_tipo_instalacion_tb

--INSERTS DE METODOS DE PAGO
INSERT INTO FIDE_METODO_PAGO_TB VALUES (1, 'Tarjeta Credito', 1);
INSERT INTO FIDE_METODO_PAGO_TB VALUES (2, 'Transferencia', 1);
INSERT INTO FIDE_METODO_PAGO_TB VALUES (3, 'PayPal', 1);
COMMIT

INSERT INTO FIDE_ESTADO_TB VALUES(6, 'Facturada');


  INSERT INTO FIDE_ORDENES_TB (CEDULA, TOTAL, ID_ESTADO, ID_METODO_PAGO) 
  VALUES (1233, 20000, 1, 1)




