--INSERTS
INSERT INTO FIDE_ESTADO_TB (ID_ESTADO, DESCRIPCION) VALUES (1, 'ACTIVO');
INSERT INTO FIDE_ASOCIADO_TB (ID_ASOCIADO, DESCRIPCION, ID_ESTADO) VALUES (1, 'PERSONA ASOCIADA', 1);
INSERT INTO FIDE_TIPO_MEMBRESIAS_TB (ID_TIPO_MEMBRESIA, COSTO, NOMBRE, DURACION_DIAS, NUM_INVITADOS, ID_ESTADO, DESCRIPCION)
VALUES (1, 20000.0, 'MEMBERESIA JAULES BÁSICA', 365, 1, 1, 'MEMBRESÍA BÁSICA, CON ACCESO LIMITADO A NUESTRAS INSTALACIONES'); 
COMMIT;

--INSERTS EN BENEFICIOS
INSERT INTO FIDE_BENEFICIOS_TB (ID_BENEFICIO, DESCRIPCION, ID_ESTADO) VALUES (1, 'Acceso al club', 1);
INSERT INTO FIDE_BENEFICIOS_TB (ID_BENEFICIO, DESCRIPCION, ID_ESTADO) VALUES (2, 'Gimnasio', 1);
INSERT INTO FIDE_BENEFICIOS_TB (ID_BENEFICIO, DESCRIPCION, ID_ESTADO) VALUES (3, 'Áreas deportivas', 1);
INSERT INTO FIDE_BENEFICIOS_TB (ID_BENEFICIO, DESCRIPCION, ID_ESTADO) VALUES (4, 'Facilidades de alojamiento', 1);
INSERT INTO FIDE_BENEFICIOS_TB (ID_BENEFICIO, DESCRIPCION, ID_ESTADO) VALUES (5, 'Facilidades para eventos', 1);
INSERT INTO FIDE_BENEFICIOS_TB (ID_BENEFICIO, DESCRIPCION, ID_ESTADO) VALUES (6, 'Acceso a piscina', 1);

--INSERTS EN BENEFICIOS MEMBRESIAS
INSERT INTO FIDE_BENEFICIOS_MEMBRESIAS_TB (ID_BENEFICIO_MEMBRESIAS, ID_TIPO_MEMB, ID_BENEFICIO, ID_ESTADO) VALUES (1, 1, 1, 1);
INSERT INTO FIDE_BENEFICIOS_MEMBRESIAS_TB (ID_BENEFICIO_MEMBRESIAS, ID_TIPO_MEMB, ID_BENEFICIO, ID_ESTADO) VALUES (2, 1, 6, 1);
COMMIT;


