--CORRERLO EN SYS

CREATE USER Administrator Identified by Admin123;

GRANT CREATE SESSION TO Administrator;
GRANT CONNECT TO ADMINISTRATOR;
GRANT RESOURCE TO ADMINISTRATOR;

--CREACION DE ROL DE ADMINISTRADOR
CREATE ROLE ADMIN_ROL;

GRANT CREATE SESSION TO ADMIN_ROL;       -- Permite conectarse a la base de datos
GRANT CREATE TABLE TO ADMIN_ROL;         -- Permite crear tablas
GRANT CREATE VIEW TO ADMIN_ROL;          -- Permite crear vistas
GRANT CREATE PROCEDURE TO ADMIN_ROL;     -- Permite crear procedimientos almacenados
GRANT CREATE SEQUENCE TO ADMIN_ROL;      -- Permite crear secuencias
GRANT CREATE ANY TABLE TO ADMIN_ROL;     -- Permite crear tablas en cualquier esquema
GRANT ALTER ANY TABLE TO ADMIN_ROL;      -- Permite modificar tablas en cualquier esquema
GRANT DROP ANY TABLE TO ADMIN_ROL;       -- Permite eliminar tablas en cualquier esquema 
GRANT CREATE TABLESPACE TO ADMIN_ROL;
GRANT CREATE PROFILE TO ADMIN_ROL;
GRANT SELECT ANY TABLE TO ADMIN_ROL;     -- Permite seleccionar datos de cualquier tabla
GRANT UPDATE ANY TABLE TO ADMIN_ROL;     -- Permite actualizar datos en cualquier tabla
GRANT ALTER ANY TABLE TO ADMIN_ROL;

GRANT ADMIN_ROL TO ADMINISTRATOR;



CREATE OR REPLACE FUNCTION FIDE_VERIFICA_CONTRASENA(
USERNAME VARCHAR2,
CONTRASENA VARCHAR2,
OLD_CONTRASENA VARCHAR2
) RETURN BOOLEAN IS

BEGIN 
    IF LENGTH(CONTRASENA)<8 THEN
    RAISE_APPLICATION_ERROR(-20001, 'La contraseña debe de tener más de 8 caracteres');
    end if;
    RETURN TRUE;
END;


CREATE PROFILE FIDE_LOS_JAULES_PROF LIMIT
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LIFE_TIME 90 --PASSWORD EXPIRA EN 90 DIAS
    PASSWORD_LOCK_TIME 1/24 --SE BLOQUEA EL USUARIO POR 1 HORA POR INTENTOS FALLIDOS, MEJORA LA SEGURIDAD
    SESSIONS_PER_USER 1
    IDLE_TIME 30 --CIERRA SESION DESPUES DE 30 MINUTOS DE INACTIVIDAD
    PASSWORD_VERIFY_FUNCTION FIDE_VERIFICA_CONTRASENA;

ALTER USER ADMINISTRATOR 
PROFILE FIDE_LOS_JAULES_PROF;

--CORRERLO EN USUARIO ADMINISTRATOR

CREATE TABLESPACE FIDE_LOS_JAULES_TBS
DATAFILE 'C:\bd\19c\oradata\ORCL\FIDE_LOS_JAULES_TBS.DBF'
SIZE 300M --Tamaño inicial del Datafile
AUTOEXTEND ON--Permitir que el Datafile crezca automaticamente cuando se llene
NEXT 30M--Incremento de tamaño cada vez que el Datafile necesite crecer
MAXSIZE 3G; --Tamaño máximo al que el Datafile puede crecer
    
    
--CREACION DE TABLAS

