--CORRERLO EN SYS

CREATE USER Administrator Identified by Admin123;

GRANT CREATE SESSION TO Administrator;
GRANT CONNECT TO ADMINISTRATOR;
GRANT RESOURCE TO ADMINISTRATOR;

--CREACION DE ROL DE ADMINISTRADOR
CREATE ROLE ADMIN_ROL;

GRANT CREATE SESSION TO ADMIN_ROL;       -- Permite conectarse a la base de datos
GRANT CREATE TABLE TO ADMIN_ROL;         -- Permite crear tablas
GRANT CREATE VIEW TO ADMIN_ROL;          -- Permite crear vistas
GRANT CREATE PROCEDURE TO ADMIN_ROL;     -- Permite crear procedimientos almacenados
GRANT CREATE SEQUENCE TO ADMIN_ROL;      -- Permite crear secuencias
GRANT CREATE ANY TABLE TO ADMIN_ROL;     -- Permite crear tablas en cualquier esquema
GRANT ALTER ANY TABLE TO ADMIN_ROL;      -- Permite modificar tablas en cualquier esquema
GRANT DROP ANY TABLE TO ADMIN_ROL;       -- Permite eliminar tablas en cualquier esquema 
GRANT CREATE TABLESPACE TO ADMIN_ROL;
GRANT CREATE PROFILE TO ADMIN_ROL;
GRANT SELECT ANY TABLE TO ADMIN_ROL;     -- Permite seleccionar datos de cualquier tabla
GRANT UPDATE ANY TABLE TO ADMIN_ROL;     -- Permite actualizar datos en cualquier tabla
GRANT ALTER ANY TABLE TO ADMIN_ROL;

GRANT ADMIN_ROL TO ADMINISTRATOR;



CREATE OR REPLACE FUNCTION FIDE_VERIFICA_CONTRASENA(
USERNAME VARCHAR2,
CONTRASENA VARCHAR2,
OLD_CONTRASENA VARCHAR2
) RETURN BOOLEAN IS

BEGIN 
    IF LENGTH(CONTRASENA)<8 THEN
    RAISE_APPLICATION_ERROR(-20001, 'La contraseña debe de tener más de 8 caracteres');
    end if;
    RETURN TRUE;
END;


CREATE PROFILE FIDE_LOS_JAULES_PROF LIMIT
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LIFE_TIME 90 --PASSWORD EXPIRA EN 90 DIAS
    PASSWORD_LOCK_TIME 1/24 --SE BLOQUEA EL USUARIO POR 1 HORA POR INTENTOS FALLIDOS, MEJORA LA SEGURIDAD
    SESSIONS_PER_USER 3
    IDLE_TIME 30 --CIERRA SESION DESPUES DE 30 MINUTOS DE INACTIVIDAD
    PASSWORD_VERIFY_FUNCTION FIDE_VERIFICA_CONTRASENA;

ALTER USER ADMINISTRATOR 
PROFILE FIDE_LOS_JAULES_PROF;


--CORRERLO EN USUARIO ADMINISTRATOR

CREATE TABLESPACE FIDE_LOS_JAULES_TBS
DATAFILE 'C:\bd\19c\oradata\ORCL\FIDE_LOS_JAULES_TBS.DBF'
SIZE 300M --Tamaño inicial del Datafile
AUTOEXTEND ON--Permitir que el Datafile crezca automaticamente cuando se llene
NEXT 30M--Incremento de tamaño cada vez que el Datafile necesite crecer
MAXSIZE 3G; --Tamaño máximo al que el Datafile puede crecer
COMMIT;  
--CREACION DE TABLAS
CREATE TABLE FIDE_ESTADO_TB (
ID_ESTADO NUMBER CONSTRAINT FIDE_ESTADO_TB_ID_ESTADO_PK PRIMARY KEY,
DESCRIPCION VARCHAR(100) NOT NULL
)TABLESPACE FIDE_LOS_JAULES_TBS;
COMMIT;
CREATE TABLE FIDE_CARGO_TB (
ID_CARGO NUMBER CONSTRAINT FIDE_CARGO_TB_ID_CARGO_PK PRIMARY KEY,
DESCRIPCION VARCHAR(100) NOT NULL,
ID_ESTADO NUMBER NOT NULL,
CONSTRAINT FIDE_CARGO_TB_CARGO_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) 
REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
)TABLESPACE FIDE_LOS_JAULES_TBS;
COMMIT;
CREATE TABLE FIDE_ASOCIADO_TB (
ID_ASOCIADO NUMBER CONSTRAINT FIDE_ASOCIADO_TB_ID_ASOCIADO_PK PRIMARY KEY,
DESCRIPCION VARCHAR(100) NOT NULL,
ID_ESTADO NUMBER NOT NULL,
CONSTRAINT FIDE_ASOCIADO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) 
REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
)TABLESPACE FIDE_LOS_JAULES_TBS;
COMMIT;
CREATE TABLE FIDE_ROLES_TB (
ID_ROL NUMBER CONSTRAINT FIDE_ROLES_TB_ID_ROL_PK PRIMARY KEY,
DESCRIPCION VARCHAR(100) NOT NULL,
ID_ESTADO NUMBER NOT NULL,
CONSTRAINT FIDE_ROLES_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) 
REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
)TABLESPACE FIDE_LOS_JAULES_TBS;

COMMIT;

CREATE TABLE FIDE_USUARIOS_TB (
CEDULA NUMBER CONSTRAINT FIDE_USUARIOS_TB_CEDULA_PK PRIMARY KEY,
FECHA_INGRESO DATE NOT NULL,
FECHA_BAJA DATE,
CONTRASENA VARCHAR2(255) NOT NULL,
NOMBRE VARCHAR2(20) NOT NULL,
APELLIDO1 VARCHAR2(20) NOT NULL,
APELLIDO2 VARCHAR2(20),
ID_ROL NUMBER NOT NULL,
ID_ASOCIADO NUMBER NOT NULL,
ID_ESTADO NUMBER NOT NULL,
ID_CARGO NUMBER,
CONSTRAINT FIDE_USUARIOS_TB_ID_CARGO_FK FOREIGN KEY (ID_CARGO) REFERENCES FIDE_CARGO_TB(ID_CARGO),
CONSTRAINT FIDE_USUARIOS_TB_ID_ROL_FK FOREIGN KEY (ID_ROL) REFERENCES FIDE_ROLES_TB(ID_ROL),
CONSTRAINT FIDE_USUARIOS_TB_ID_ASOCIADO_FK FOREIGN KEY (ID_ASOCIADO) REFERENCES FIDE_ASOCIADO_TB(ID_ASOCIADO),
CONSTRAINT FIDE_USUARIOS_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE FIDE_LOS_JAULES_TBS;

COMMIT;

CREATE TABLE FIDE_TELEFONOS_TB (
ID_TELEFONO NUMBER CONSTRAINT FIDE_TELEFONOS_TB_ID_TELEFONO_PK PRIMARY KEY,
DESCRIPCION VARCHAR2(100),
CEDULA NUMBER NOT NULL,
ID_ESTADO NUMBER NOT NULL,
CONSTRAINT FIDE_TELEFONOS_TB_CEDULA_FK FOREIGN KEY (CEDULA)
REFERENCES FIDE_USUARIOS_TB(CEDULA),
CONSTRAINT FIDE_TELEFONOS_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) 
REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE FIDE_LOS_JAULES_TBS;

--CREACION TABLA INVITADOS

CREATE TABLE FIDE_INVITADOS_TB (
ID_INVITADO NUMBER CONSTRAINT FIDE_INVITADOS_TB_ID_INVITADO_PK PRIMARY KEY,
CEDULA NUMBER NOT NULL,
FECHA_REGISTRO DATE NOT NULL,
ID_ESTADO NUMBER NOT NULL,
CEDULA_MIEMBRO NUMBER NOT NULL,
CONSTRAINT FIDE_INVITADOS_TB_CEDULA_MIEMBRO_FK FOREIGN KEY (CEDULA_MIEMBRO)
REFERENCES FIDE_USUARIOS_TB(CEDULA),
CONSTRAINT FIDE_INVITADOS_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) 
REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE FIDE_LOS_JAULES_TBS;

--CREACION DE TABLA

CREATE TABLE FIDE_EMAIL_TB(
ID_EMAIL NUMBER CONSTRAINT FIDE_EMAIL_TB_ID_EMAIL_PK PRIMARY KEY,
CEDULA NUMBER NOT NULL,
EMAIL VARCHAR2(100) CONSTRAINT FIDE_EMAIL_TB_EMAIL_UNIQUE UNIQUE,
CONSTRAINT FIDE_EMAIL_TB_CEDULA_FK FOREIGN KEY (CEDULA) 
REFERENCES FIDE_USUARIOS_TB(CEDULA)
) TABLESPACE FIDE_LOS_JAULES_TBS;

--CREACION DE TABLA PROVINCIAS

CREATE TABLE FIDE_PROVINCIAS_TB (
ID_PROVINCIA NUMBER CONSTRAINT FIDE_PROVINCIAS_TB_ID_PROVINCIA_PK PRIMARY KEY, 
NOMBRE VARCHAR2(50) NOT NULL
)
TABLESPACE FIDE_LOS_JAULES_TBS;


--CREACION DE TABLA CANTONES
CREATE TABLE FIDE_CANTONES_TB (
ID_CANTON NUMBER CONSTRAINT FIDE_CANTONES_TB_ID_CANTON_PK PRIMARY KEY, 
NOMBRE VARCHAR2(50) NOT NULL,
ID_PROVINCIA NUMBER NOT NULL,
CONSTRAINT FIDE_CANTONES_TB_PROVINCIA_FK FOREIGN KEY (ID_PROVINCIA)
REFERENCES FIDE_PROVINCIAS_TB (ID_PROVINCIA)
)
TABLESPACE FIDE_LOS_JAULES_TBS;


--CREACION DE TABLA DISTRITOS
CREATE TABLE FIDE_DISTRITOS_TB (
ID_DISTRITO NUMBER CONSTRAINT FIDE_DISTRITOS_TB_ID_DISTRITO_PK PRIMARY KEY, 
NOMBRE VARCHAR2(50) NOT NULL,
ID_CANTON NUMBER NOT NULL,
CONSTRAINT FIDE_DISTRITOS_TB_CANTON_FK FOREIGN KEY (ID_CANTON)
REFERENCES FIDE_CANTONES_TB (ID_CANTON)
)
TABLESPACE FIDE_LOS_JAULES_TBS;
--CREACION DE TABLA PROVEEDORES
CREATE TABLE FIDE_PROVEEDORES_TB (
ID_PROVEEDOR NUMBER CONSTRAINT FIDE_PROVEEDORES_TB_ID_PROVEEDOR_PK PRIMARY KEY,
ID_ESTADO NUMBER NOT NULL,
NOMBRE VARCHAR2(50) NOT NULL,
TELEFONO NUMBER NOT NULL,
EMAIL VARCHAR2(100) UNIQUE,
CONSTRAINT FIDE_PROVEEDORES_TB_ESTADO_FK FOREIGN KEY (ID_ESTADO)
REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
) TABLESPACE FIDE_LOS_JAULES_TBS;


--CREACION DE TABLA DIRECCIONES
CREATE TABLE FIDE_DIRECCIONES_TB (
ID_DIRECCION NUMBER CONSTRAINT FIDE_DIRECCIONES_TB_ID_DIRECCION_PK PRIMARY KEY, 
DIRECCION_EXACTA VARCHAR2(200) NOT NULL,
CEDULA NUMBER,
ID_DISTRITO NUMBER NOT NULL,
ID_PROVEEDOR NUMBER,
CONSTRAINT FIDE_DIRECCIONES_TB_DISTRITO_FK FOREIGN KEY (ID_DISTRITO)
REFERENCES FIDE_DISTRITOS_TB (ID_DISTRITO),
CONSTRAINT FIDE_DIRECCIONES_TB_CEDULA_FK FOREIGN KEY (CEDULA)
REFERENCES FIDE_USUARIOS_TB (CEDULA),
CONSTRAINT FIDE_DIRECCIONES_TB_ID_PROVEEDOR_FK FOREIGN KEY (ID_PROVEEDOR)
REFERENCES FIDE_PROVEEDORES_TB (ID_PROVEEDOR)
)
TABLESPACE FIDE_LOS_JAULES_TBS;

--CREACION DE PRODUCTOS
CREATE TABLE FIDE_PRODUCTOS_TB (
ID_PRODUCTO NUMBER CONSTRAINT FIDE_PRODUCTOS_TB_ID_PRODUCTO_PK PRIMARY KEY,
COSTO DECIMAL(10,2),
NOMBRE VARCHAR2(50),
ID_ESTADO NUMBER,
CONSTRAINT FIDE_PRODUCTOS_TB_ESTADO_FK FOREIGN KEY(ID_ESTADO)
REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
) TABLESPACE FIDE_LOS_JAULES_TBS;

--CREACION DE PRODUCTOS PROVEEDOR

CREATE TABLE FIDE_PRODUCTOS_PROVEEDOR_TB (
ID_PROD_PROVEEDOR NUMBER CONSTRAINT FIDE_PRODUCTOS_PROVEEDOR_TB_ID_PROVEEDOR_PK PRIMARY KEY,
ID_PROVEEDOR NUMBER NOT NULL,
ID_PRODUCTO NUMBER NOT NULL,
ID_ESTADO NUMBER NOT NULL,
CONSTRAINT FIDE_PRODUCTOS_PROVEEDOR_TB_ID_PROVEEDOR_FK FOREIGN KEY (ID_PROVEEDOR)
REFERENCES FIDE_PROVEEDORES_TB (ID_PROVEEDOR),
CONSTRAINT FIDE_PRODUCTOS_PROVEEDOR_TB_ID_PRODUCTO_FK FOREIGN KEY (ID_PRODUCTO)
REFERENCES FIDE_PRODUCTOS_TB (ID_PRODUCTO),
CONSTRAINT FIDE_PRODUCTOS_PROVEEDOR_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
) TABLESPACE FIDE_LOS_JAULES_TBS;


--CREACION DE INVENTARIO
CREATE TABLE FIDE_INVENTARIO_TB (
ID_INVENTARIO NUMBER CONSTRAINT FIDE_INVENTARIO_TB_ID_INVENTARIO_PK PRIMARY KEY,
CANTIDAD NUMBER NOT NULL,
ID_PRODUCTO NUMBER,
CANTIDAD_MINIMA NUMBER,
CONSTRAINT FIDE_INVENTARIO_TB_ID_PRODUCTO_FK FOREIGN KEY (ID_PRODUCTO)
REFERENCES FIDE_PRODUCTOS_TB (ID_PRODUCTO)
) TABLESPACE FIDE_LOS_JAULES_TBS;

--CREACION DE SERVICIOS
CREATE TABLE FIDE_SERVICIOS_TB (
ID_SERVICIO NUMBER CONSTRAINT FIDE_SERVICIOS_TB_ID_SERVICIO_PK PRIMARY KEY,
DESCRIPCION VARCHAR2(200),
ID_ESTADO NUMBER NOT NULL,
CONSTRAINT FIDE_SERVICIOS_TB_ESTADO_FK FOREIGN KEY (ID_ESTADO)
REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
) TABLESPACE FIDE_LOS_JAULES_TBS;



--CREACION DE SERVICIOS_PROVEEDOR
CREATE TABLE FIDE_SERVICIOS_PROVEEDOR_TB (
ID_SERVICIO_PROVEEDOR NUMBER CONSTRAINT FIDE_SERV_PROV_TB_ID_SERV_PROVEEDOR_PK PRIMARY KEY,
ID_PROVEEDOR NUMBER NOT NULL,
ID_SERVICIO NUMBER NOT NULL,
ID_ESTADO NUMBER NOT NULL,
CONSTRAINT FIDE_SERVICIOS_PROVEEDOR_TB_PROVEEDOR_FK FOREIGN KEY (ID_PROVEEDOR)
REFERENCES FIDE_PROVEEDORES_TB (ID_PROVEEDOR),
CONSTRAINT FIDE_SERVICIOS_PROVEEDOR_TB_SERVICIOS_FK FOREIGN KEY (ID_SERVICIO)
REFERENCES FIDE_SERVICIOS_TB (ID_SERVICIO),
CONSTRAINT FIDE_SERVICIOS_PROVEEDOR_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
) TABLESPACE FIDE_LOS_JAULES_TBS;

--CREACION DE METODO PAGO
CREATE TABLE FIDE_METODO_PAGO_TB (
ID_METODO_PAGO NUMBER CONSTRAINT FIDE_METODO_PAGP_TB_ID_METODO_PAGO_PK PRIMARY KEY,
DESCRIPCION VARCHAR2(100),
ID_ESTADO NUMBER,
CONSTRAINT FIDE_METODO_PAGO_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
) TABLESPACE FIDE_LOS_JAULES_TBS;


--CREACION DE TABLA CARRITO
CREATE TABLE FIDE_CARRITO_TB (
ID_CARRITO NUMBER CONSTRAINT FIDE_CARRITO_TB_ID_CARRITO_PK PRIMARY KEY,
CEDULA NUMBER,
CONSTRAINT FIDE_CARRITO_TB_CEDULA_PK FOREIGN KEY (CEDULA)
REFERENCES FIDE_USUARIOS_TB(CEDULA)

) TABLESPACE FIDE_LOS_JAULES_TBS;


--CREACION DE TABLA ORDENES
CREATE TABLE FIDE_ORDENES_TB (
ID_ORDEN NUMBER CONSTRAINT FIDE_ORDENES_TB_ID_ORDEN_PK PRIMARY KEY,
CEDULA NUMBER,
TOTAL DECIMAL(10,2),
ID_ESTADO NUMBER,
ID_METODO_PAGO NUMBER,
CONSTRAINT FIDE_ORDENES_TB_CEDULA_PK FOREIGN KEY (CEDULA)
REFERENCES FIDE_USUARIOS_TB(CEDULA),
CONSTRAINT FIDE_ORDENES_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
REFERENCES FIDE_ESTADO_TB (ID_ESTADO),
CONSTRAINT FIDE_ORDENES_METODO_PAGO__FK FOREIGN KEY (ID_METODO_PAGO)
REFERENCES FIDE_METODO_PAGO_TB (ID_METODO_PAGO)
) TABLESPACE FIDE_LOS_JAULES_TBS;

--CREACION DE TABLA TIPO INSTALACION
CREATE TABLE FIDE_TIPO_INSTALACION_TB (
ID_TIPO_INSTALACION NUMBER CONSTRAINT FIDE_TIPO_INSTALACION_TB_ID_TIPO_INSTALACION_PK PRIMARY KEY,
DESCRIPCION VARCHAR2(100),
ID_ESTADO NUMBER,
CONSTRAINT FIDE_TIPO_INSTALACION_TB_ID_ESTADO_FK FOREIGN KEY(ID_ESTADO)
REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
) TABLESPACE FIDE_LOS_JAULES_TBS;


--CREACION INSTALACIONES

CREATE TABLE FIDE_INSTALACIONES_TB (
ID_INSTALACION NUMBER CONSTRAINT FIDE_INSTALACIONES_TB_ID_INSTALACION_PK PRIMARY KEY,
NOMBRE VARCHAR2(50),
COSTO DECIMAL(10,2),
ID_TIPO_INSTALACION NUMBER,
CAPACIDAD NUMBER,
ID_ESTADO NUMBER,
CONSTRAINT FIDE_INSTALACIONES_TB_ID_ESTADO_FK FOREIGN KEY(ID_ESTADO)
REFERENCES FIDE_ESTADO_TB (ID_ESTADO),
CONSTRAINT FIDE_INSTALACIONES_TB_ID_TIPO_INSTALACION_FK FOREIGN KEY(ID_TIPO_INSTALACION)
REFERENCES FIDE_TIPO_INSTALACION_TB (ID_TIPO_INSTALACION)
)TABLESPACE FIDE_LOS_JAULES_TBS;

--CREACION EVENTOS
CREATE TABLE FIDE_EVENTOS_TB (
ID_EVENTO NUMBER CONSTRAINT FIDE_EVENTOS_TB_ID_EVENTO_PK PRIMARY KEY,
NOMBRE VARCHAR2(50) NOT NULL,
DESCRIPCION VARCHAR2(100) NOT NULL, 
HORA TIMESTAMP NOT NULL,
FECHA DATE NOT NULL,
ID_ESTADO NUMBER NOT NULL,
ID_INSTALACION NUMBER,
CAPACIDAD NUMBER NOT NULL,
CONSTRAINT FIDE_EVENTOS_TB_ID_ESTADO_FK FOREIGN KEY(ID_ESTADO)
REFERENCES FIDE_ESTADO_TB (ID_ESTADO),
CONSTRAINT FIDE_EVENTOS_TB_ID_INSTALACION_FK FOREIGN KEY (ID_INSTALACION)
REFERENCES FIDE_INSTALACIONES_TB (ID_INSTALACION)
) TABLESPACE FIDE_LOS_JAULES_TBS;


--CREACION DE RESERVAS

CREATE TABLE FIDE_RESERVAS_TB (
ID_RESERVA NUMBER CONSTRAINT FIDE_RESERVAS_TB_ID_RESERVA_PK PRIMARY KEY,
CEDULA NUMBER,
FECHA_INICIO DATE,
FECHA_FIN DATE,
HORA_INICIO TIMESTAMP,
HORA_FIN TIMESTAMP,
ID_INSTALACION NUMBER,
ID_ESTADO NUMBER,
NUM_PERSONAS NUMBER,
CONSTRAINT FIDE_RESERVAS_TB_ID_INSTALACION_FK FOREIGN KEY (ID_INSTALACION)
REFERENCES FIDE_INSTALACIONES_TB (ID_INSTALACION),
CONSTRAINT FIDE_RESERVAS_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
REFERENCES FIDE_ESTADO_TB,
CONSTRAINT FIDE_RESERVAS_TB_CEDULA_FK FOREIGN KEY (CEDULA)
REFERENCES FIDE_USUARIOS_TB (CEDULA)
) TABLESPACE FIDE_LOS_JAULES_TBS;

--CREACION REGISTRO EVENTOS

CREATE TABLE FIDE_REGISTRO_EVENTOS_TB (
ID_REGISTRO NUMBER CONSTRAINT  FIDE_REGISTRO_EVENTOS_TB_ID_REGISTRO_PK PRIMARY KEY,
CEDULA NUMBER,
ID_INVITADO NUMBER,
ID_EVENTO NUMBER,
FECHA_REGISTRO DATE,
CONSTRAINT FIDE_REGISTRO_EVENTOS_TB_CEDULA_FK FOREIGN KEY (CEDULA)
REFERENCES FIDE_USUARIOS_TB (CEDULA),
CONSTRAINT FIDE_REGISTRO_EVENTOS_ID_EVENTO_FK FOREIGN KEY (ID_EVENTO)
REFERENCES FIDE_EVENTOS_TB (ID_EVENTO),
CONSTRAINT FIDE_REGISTRO_EVENTOS_TB_ID_INVITADO_FK FOREIGN KEY (ID_INVITADO)
REFERENCES FIDE_INVITADOS_TB (ID_INVITADO)
) TABLESPACE FIDE_LOS_JAULES_TBS;

CREATE TABLE FIDE_FACTURA_TB (
ID_FACTURA NUMBER CONSTRAINT FIDE_FACTURA_TB_ID_FACTURA_PK PRIMARY KEY,
ID_ORDEN NUMBER,
FECHA_EMISION DATE,
SUBTOTAL DECIMAL(10,2),
TOTAL DECIMAL(10,2),
IVA DECIMAL(10,2),
CONSTRAINT FIDE_FACTURA_TB_ID_ORDEN_FK FOREIGN KEY(ID_ORDEN)
REFERENCES FIDE_ORDENES_TB (ID_ORDEN)
) TABLESPACE FIDE_LOS_JAULES_TBS;

--TABLA BENEFICIOS
CREATE TABLE FIDE_BENEFICIOS_TB (
ID_BENEFICIO NUMBER CONSTRAINT FIDE_BENEFICIOS_TB_ID_BENEFICIOS_PK PRIMARY KEY,
DESCRIPCION VARCHAR2(100),
ID_ESTADO NUMBER NOT NULL,
CONSTRAINT FIDE_BENEFICIOS_TB_ID_ESTADO FOREIGN KEY(ID_ESTADO)
REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
)TABLESPACE FIDE_LOS_JAULES_TBS;

--TABLA TIPO_MEMBRESIAS
CREATE TABLE FIDE_TIPO_MEMBRESIAS_TB (
ID_TIPO_MEMBRESIA NUMBER CONSTRAINT FIDE_TIPO_MEMBRESIAS_TB_ID_TIPO_MEMBRESIA_PK PRIMARY KEY,
COSTO DECIMAL(10,2),
DURACION_DIAS NUMBER NOT NULL,
DESCRIPCION VARCHAR2(200) NOT NULL,
NOMBRE VARCHAR2(50) NOT NULL,
NUM_IMVITADOS NUMBER,
ID_ESTADO NUMBER,
CONSTRAINT FIDE_TIPO_MEMBRESIAS_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
) TABLESPACE FIDE_LOS_JAULES_TBS;

--TABLA BENEFICIOS MEMBRESIAS
CREATE TABLE FIDE_BENEFICIOS_MEMBRESIAS_TB (
ID_BENEFICIO_MEMBRESIAS NUMBER CONSTRAINT FIDE_BENEFICIOS_MEMBRESIAS_TB_ID_MEMBRESIA_PK PRIMARY KEY,
ID_TIPO_MEMB NUMBER NOT NULL,
ID_BENEFICIO NUMBER NOT NULL,
ID_ESTADO NUMBER NOT NULL,
CONSTRAINT FIDE_BENEFICIOS_MEMBRESIAS_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
REFERENCES FIDE_ESTADO_TB (ID_ESTADO),
CONSTRAINT FIDE_BENEFICIOS_MEMBRESIAS_TB_ID_BENEFICIO_FK FOREIGN KEY (ID_BENEFICIO)
REFERENCES FIDE_BENEFICIOS_TB (ID_BENEFICIO),
CONSTRAINT FIDE_BENEFICIOS_MEMBRESIAS_TB_ID_TIPO_MEMB_FK FOREIGN KEY (ID_TIPO_MEMB)
REFERENCES FIDE_TIPO_MEMBRESIAS_TB (ID_TIPO_MEMBRESIA)
) TABLESPACE FIDE_LOS_JAULES_TBS;

--TABLE CARRITO ITEMS

CREATE TABLE FIDE_CARRITO_ITEMS_TB (
ID_ITEM NUMBER CONSTRAINT FIDE_CARRITO_ITEMS_TB_ID_ITEM_PK PRIMARY KEY,
ID_CARRITO NUMBER,
ID_RESERVA NUMBER,
ID_TIPO_MEMBRESIA NUMBER,
CANTIDAD NUMBER,
PRECIO DECIMAL(10,2),
CONSTRAINT FIDE_CARRITO_ITEMS_TB_ID_CARRITO_FK FOREIGN KEY (ID_CARRITO)
REFERENCES FIDE_CARRITO_TB (ID_CARRITO),
CONSTRAINT FIDE_CARRITO_ITEMS_TB_ID_RESERVA_FK FOREIGN KEY (ID_RESERVA)
REFERENCES FIDE_RESERVAS_TB (ID_RESERVA),
CONSTRAINT FIDE_CARRITO_ITEMS_TB_TIPO_MEMBRESIA_FK FOREIGN KEY (ID_TIPO_MEMBRESIA)
REFERENCES FIDE_TIPO_MEMBRESIAS_TB (ID_TIPO_MEMBRESIA)
) TABLESPACE FIDE_LOS_JAULES_TBS;

CREATE TABLE FIDE_ORDEN_ITEMS_TB (
ID_ORDEN_ITEM NUMBER CONSTRAINT FIDE_ORDEN_ITEMS_TB_ID_ORDEN_ITEM_PK PRIMARY KEY,
ID_ORDEN NUMBER,
ID_RESERVA NUMBER,
ID_TIPO_MEMBRESIA NUMBER,
CANTIDAD NUMBER,
PRECIO DECIMAL(10,2),
CONSTRAINT FIDE_ORDEN_ITEMS_TB_ID_ORDEN_FK FOREIGN KEY (ID_ORDEN)
REFERENCES FIDE_ORDENES_TB (ID_ORDEN),
CONSTRAINT FIDE_ORDEN_ITEMS_TB_ID_RESERVA_FK FOREIGN KEY (ID_RESERVA)
REFERENCES FIDE_RESERVAS_TB (ID_RESERVA),
CONSTRAINT FIDE_ORDEN_ITEMS_TB_TIPO_MEMBRESIA_FK FOREIGN KEY (ID_TIPO_MEMBRESIA)
REFERENCES FIDE_TIPO_MEMBRESIAS_TB (ID_TIPO_MEMBRESIA)
) TABLESPACE FIDE_LOS_JAULES_TBS;

COMMIT;