--CREACION DE PAQUETE PARA ALMACENAR TODO LO RELACIONADO A LAS MEMBRESIAS

CREATE OR REPLACE PACKAGE FIDE_LOS_JAULES_MEMBRESIAS_PKG 
AS
PROCEDURE FIDE_TIPO_MEMBRESIAS_TB_OBTENER_MEMBRESIAS_SP (P_CURSOR OUT SYS_REFCURSOR);
PROCEDURE FIDE_TIPO_MEMBRESIAS_TB_GET_MEMBRESIA_SP (P_CURSOR OUT SYS_REFCURSOR, P_ID IN NUMBER);
PROCEDURE FIDE_TIPO_MEMBRESIAS_TB_GET_BENEFICIOS_SP (P_CURSOR OUT SYS_REFCURSOR, P_ID IN NUMBER);
PROCEDURE FIDE_TIPO_MEMBRESIAS_TB_GET_BENEFICIOS_MEMBRESIAS_SP (P_CURSOR OUT SYS_REFCURSOR);
PROCEDURE FIDE_TIPO_MEMBRESIAS_TB_GET_ALL_BENEFICIOS_SP (P_CURSOR OUT SYS_REFCURSOR);
PROCEDURE FIDE_TIPO_MEMBRESIAS_TB_ASOCIAR_BENEFICIOS_SP (P_ID_BENEFICIO IN NUMBER, P_ID_MEMBRESIA IN NUMBER);
PROCEDURE FIDE_MEMBRESIAS_TB_GET_MEMBRESIA_USUARIO_SP (P_CURSOR OUT SYS_REFCURSOR, P_CEDULA IN NUMBER);
PROCEDURE FIDE_MEMBRESIAS_TB_MODIFICAR_MEMBRESIA_SP (P_ID_MEMBRESIA IN NUMBER, P_NOMBRE 
IN VARCHAR2, P_COSTO IN NUMBER, P_DURACION IN NUMBER, P_DESCRIPCION IN varchar2, P_NUMERO IN NUMBER);
PROCEDURE FIDE_MEMBRESIAS_TB_ELIMINAR_MEMBRESIA_SP (P_ID_MEMBRESIA IN NUMBER);
PROCEDURE FIDE_MEMBRESIAS_TB_CREAR_MEMBRESIA_SP ( P_NOMBRE 
IN VARCHAR2, P_COSTO IN NUMBER, P_DURACION IN NUMBER, P_DESCRIPCION IN varchar2, P_NUMERO IN NUMBER);
PROCEDURE FIDE_MEMBRESIAS_TB_ELIMINAR_BENEFICIO_ASIGNADO_SP (P_ID_BENEFICIO IN NUMBER);
PROCEDURE FIDE_MEMBRESIAS_TB_ELIMINAR_BENEFICIO_SP (P_ID_BENEFICIO IN NUMBER);
PROCEDURE FIDE_MEMBRESIAS_TB_EDITAR_BENEFICIO (P_ID_BENEFICIO IN NUMBER, P_DESCRIPCION IN VARCHAR2);
PROCEDURE FIDE_BENEFICIOS_TB_AGREGAR_SP (P_DESCRIPCION IN VARCHAR2);
PROCEDURE FIDE_MEMBRESIAS_TB_ACTUALIZAR_PASE_DIARIO_SP (P_ID_MEMBRESIA IN NUMBER, P_FECHA_INICIO IN DATE, P_RESULTADO OUT VARCHAR2);
PROCEDURE FIDE_MEMBRESIAS_TB_CANCELAR_SP (P_ID_MEMBRESIA IN NUMBER, P_RESULTADO OUT VARCHAR2);
END FIDE_LOS_JAULES_MEMBRESIAS_PKG;

CREATE OR REPLACE PACKAGE BODY FIDE_LOS_JAULES_MEMBRESIAS_PKG  AS

PROCEDURE FIDE_MEMBRESIAS_TB_CANCELAR_SP (P_ID_MEMBRESIA IN NUMBER, P_RESULTADO OUT VARCHAR2) AS
RESULTADO VARCHAR2(200);
BEGIN
    UPDATE FIDE_MEMBRESIAS_TB SET ID_ESTADO = 0 WHERE ID_MEMBRESIA = P_ID_MEMBRESIA;
    COMMIT;
    P_RESULTADO := 'Membresía cancelada exitosamente. Gracias!';
    RETURN;
END FIDE_MEMBRESIAS_TB_CANCELAR_SP;

PROCEDURE FIDE_MEMBRESIAS_TB_ACTUALIZAR_PASE_DIARIO_SP (P_ID_MEMBRESIA IN NUMBER, P_FECHA_INICIO IN DATE,
P_RESULTADO OUT VARCHAR2) AS
V_FECHA_ACTUALIZADA NUMBER;
 V_FECHA_ACTUAL DATE;
BEGIN
    SELECT FECHA_ACTUALIZADA, FECHA_INICIO INTO V_FECHA_ACTUALIZADA, V_FECHA_ACTUAL
    FROM FIDE_MEMBRESIAS_TB WHERE ID_MEMBRESIA = P_ID_MEMBRESIA;
    
    IF V_FECHA_ACTUALIZADA = 1 THEN
        P_RESULTADO := 'Ya actualizaste la fecha del pase diario una vez, no es permitido dos veces.';
        RETURN;
    END IF;
     IF P_FECHA_INICIO <= V_FECHA_ACTUAL THEN
        P_RESULTADO := 'La nueva fecha debe ser mayor a la actual.';
        RETURN;
    END IF;
    
    UPDATE FIDE_MEMBRESIAS_TB
    SET FECHA_INICIO = P_FECHA_INICIO, FECHA_FIN = P_FECHA_INICIO,
        FECHA_ACTUALIZADA = 1
    WHERE ID_MEMBRESIA = P_ID_MEMBRESIA;

    P_RESULTADO := 'Fecha actualizada correctamente. Ahora podrás ingresar ese día al club, y registrarte
    en eventos';
    RETURN;
EXCEPTION
    WHEN OTHERS THEN
        P_RESULTADO := 'Error al actualizar fecha.';
END FIDE_MEMBRESIAS_TB_ACTUALIZAR_PASE_DIARIO_SP;


PROCEDURE FIDE_MEMBRESIAS_TB_CREAR_MEMBRESIA_SP (P_NOMBRE 
IN VARCHAR2, P_COSTO IN NUMBER, P_DURACION IN NUMBER, P_DESCRIPCION IN varchar2, P_NUMERO IN NUMBER) AS
BEGIN
    INSERT INTO FIDE_TIPO_MEMBRESIAS_TB (NOMBRE, COSTO, DURACION_DIAS, DESCRIPCION,
    NUM_INVITADOS, ID_ESTADO) VALUES (P_NOMBRE, P_COSTO, P_DURACION, P_DESCRIPCION, P_NUMERO, 1);
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20001, SQLERRM);
END FIDE_MEMBRESIAS_TB_CREAR_MEMBRESIA_SP;

PROCEDURE FIDE_MEMBRESIAS_TB_ELIMINAR_MEMBRESIA_SP (P_ID_MEMBRESIA IN NUMBER) AS
BEGIN
    UPDATE FIDE_TIPO_MEMBRESIAS_TB SET ID_ESTADO = 0 WHERE ID_TIPO_MEMBRESIA = P_ID_MEMBRESIA;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20001, SQLERRM);
END FIDE_MEMBRESIAS_TB_ELIMINAR_MEMBRESIA_SP;

PROCEDURE FIDE_MEMBRESIAS_TB_MODIFICAR_MEMBRESIA_SP (P_ID_MEMBRESIA IN NUMBER, P_NOMBRE 
IN VARCHAR2, P_COSTO IN NUMBER, P_DURACION IN NUMBER, P_DESCRIPCION IN varchar2, P_NUMERO IN NUMBER) 
AS
BEGIN
    UPDATE FIDE_TIPO_MEMBRESIAS_TB SET COSTO = P_COSTO, DURACION_DIAS = P_DURACION,
    NOMBRE = P_NOMBRE, NUM_INVITADOS = P_NUMERO, DESCRIPCION = P_DESCRIPCION,
    ID_ESTADO = 1 WHERE ID_TIPO_MEMBRESIA = P_ID_MEMBRESIA;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20001, SQLERRM);
END FIDE_MEMBRESIAS_TB_MODIFICAR_MEMBRESIA_SP;
--OBTENER LA MEMBRESIA DEL USUARIO
PROCEDURE FIDE_MEMBRESIAS_TB_GET_MEMBRESIA_USUARIO_SP (P_CURSOR OUT SYS_REFCURSOR, P_CEDULA IN NUMBER)
AS
BEGIN
OPEN P_CURSOR FOR
  SELECT M.ID_MEMBRESIA, M.FECHA_INICIO, M.FECHA_FIN, M.ID_ESTADO, T.NOMBRE, T.NUM_INVITADOS, M.ID_TIPO_MEMBRESIA
  FROM FIDE_MEMBRESIAS_TB M
  INNER JOIN FIDE_TIPO_MEMBRESIAS_TB T
    ON M.ID_TIPO_MEMBRESIA = T.ID_TIPO_MEMBRESIA
  WHERE M.CEDULA = P_CEDULA
    AND M.ID_ESTADO = 1;

END FIDE_MEMBRESIAS_TB_GET_MEMBRESIA_USUARIO_SP;

PROCEDURE FIDE_TIPO_MEMBRESIAS_TB_OBTENER_MEMBRESIAS_SP (P_CURSOR OUT SYS_REFCURSOR)
IS
    V_CONTAR NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_CONTAR FROM FIDE_TIPO_MEMBRESIAS_TB WHERE ID_ESTADO = 1;
    IF V_CONTAR> 0 THEN
    OPEN P_CURSOR FOR
    SELECT ID_TIPO_MEMBRESIA, COSTO, DURACION_DIAS, NOMBRE, NUM_INVITADOS, DESCRIPCION
    FROM FIDE_TIPO_MEMBRESIAS_TB
    WHERE ID_ESTADO = 1;
    
    ELSE 
     OPEN p_cursor FOR
        SELECT 'No existen membresías disponibles' AS MENSAJE, NULL AS ID_TIPO_MEMBRESIA, NULL AS COSTO, NULL AS DURACION_DIAS, NULL AS NOMBRE, NULL AS NUM_INVITADOS FROM DUAL;
    END IF;
END FIDE_TIPO_MEMBRESIAS_TB_OBTENER_MEMBRESIAS_SP;

PROCEDURE FIDE_TIPO_MEMBRESIAS_TB_GET_MEMBRESIA_SP (P_CURSOR OUT SYS_REFCURSOR, P_ID IN NUMBER) 
AS
BEGIN
    OPEN P_CURSOR FOR 
    SELECT ID_TIPO_MEMBRESIA, COSTO, DURACION_DIAS, NOMBRE, NUM_INVITADOS, DESCRIPCION
    FROM FIDE_TIPO_MEMBRESIAS_TB
    WHERE ID_TIPO_MEMBRESIA = P_ID;
END FIDE_TIPO_MEMBRESIAS_TB_GET_MEMBRESIA_SP;

PROCEDURE FIDE_TIPO_MEMBRESIAS_TB_GET_BENEFICIOS_SP (P_CURSOR OUT SYS_REFCURSOR, P_ID IN NUMBER)
AS
BEGIN
    OPEN P_CURSOR FOR
    SELECT BM.ID_BENEFICIO_MEMBRESIAS, BM.ID_TIPO_MEMB, BM.ID_BENEFICIO, BM.ID_ESTADO, B.DESCRIPCION, M.NOMBRE
    FROM FIDE_BENEFICIOS_MEMBRESIAS_TB BM INNER JOIN FIDE_BENEFICIOS_TB B ON BM.ID_BENEFICIO = B.ID_BENEFICIO
    INNER JOIN FIDE_TIPO_MEMBRESIAS_TB M ON M.ID_TIPO_MEMBRESIA = BM.ID_TIPO_MEMB
    WHERE M.ID_TIPO_MEMBRESIA = P_ID AND BM.ID_ESTADO = 1;
END FIDE_TIPO_MEMBRESIAS_TB_GET_BENEFICIOS_SP;

PROCEDURE FIDE_TIPO_MEMBRESIAS_TB_GET_BENEFICIOS_MEMBRESIAS_SP (P_CURSOR OUT SYS_REFCURSOR)
AS 
BEGIN
 OPEN P_CURSOR FOR
    SELECT BM.ID_BENEFICIO_MEMBRESIAS, BM.ID_TIPO_MEMB, BM.ID_BENEFICIO, BM.ID_ESTADO, B.DESCRIPCION, M.NOMBRE
    FROM FIDE_BENEFICIOS_MEMBRESIAS_TB BM INNER JOIN FIDE_BENEFICIOS_TB B ON BM.ID_BENEFICIO = B.ID_BENEFICIO
    INNER JOIN FIDE_TIPO_MEMBRESIAS_TB M ON M.ID_TIPO_MEMBRESIA = BM.ID_TIPO_MEMB WHERE BM.ID_ESTADO = 1;
END FIDE_TIPO_MEMBRESIAS_TB_GET_BENEFICIOS_MEMBRESIAS_SP;

PROCEDURE FIDE_TIPO_MEMBRESIAS_TB_GET_ALL_BENEFICIOS_SP (P_CURSOR OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN P_CURSOR FOR
    SELECT ID_BENEFICIO, DESCRIPCION, ID_ESTADO FROM FIDE_BENEFICIOS_TB
    WHERE ID_ESTADO = 1;
END FIDE_TIPO_MEMBRESIAS_TB_GET_ALL_BENEFICIOS_SP;

PROCEDURE FIDE_TIPO_MEMBRESIAS_TB_ASOCIAR_BENEFICIOS_SP (P_ID_BENEFICIO IN NUMBER, P_ID_MEMBRESIA IN NUMBER) AS
V_CONTAR NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_CONTAR FROM FIDE_BENEFICIOS_MEMBRESIAS_TB
    WHERE ID_TIPO_MEMB = P_ID_MEMBRESIA AND ID_BENEFICIO = P_ID_BENEFICIO AND ID_ESTADO =1;
    
    IF V_CONTAR = 0 THEN
        INSERT INTO FIDE_BENEFICIOS_MEMBRESIAS_TB (ID_BENEFICIO, ID_TIPO_MEMB, ID_ESTADO)
        VALUES (P_ID_BENEFICIO, P_ID_MEMBRESIA, 1);
        COMMIT;
    ELSE
        RAISE_APPLICATION_ERROR(-20001, 'El beneficio seleccionado ya está asignado a la membresía');
    END IF;
EXCEPTION 
    WHEN OTHERS THEN 
        RAISE_APPLICATION_ERROR(-20001, SQLERRM);
END FIDE_TIPO_MEMBRESIAS_TB_ASOCIAR_BENEFICIOS_SP;

PROCEDURE FIDE_MEMBRESIAS_TB_ELIMINAR_BENEFICIO_ASIGNADO_SP (P_ID_BENEFICIO IN NUMBER) AS
BEGIN
    UPDATE FIDE_BENEFICIOS_MEMBRESIAS_TB SET ID_ESTADO = 0 WHERE ID_BENEFICIO_MEMBRESIAS = P_ID_BENEFICIO;
    COMMIT;
EXCEPTION
     WHEN OTHERS THEN 
        RAISE_APPLICATION_ERROR(-20001, SQLERRM);

END FIDE_MEMBRESIAS_TB_ELIMINAR_BENEFICIO_ASIGNADO_SP;

PROCEDURE FIDE_MEMBRESIAS_TB_ELIMINAR_BENEFICIO_SP (P_ID_BENEFICIO IN NUMBER) AS
BEGIN
    UPDATE FIDE_BENEFICIOS_MEMBRESIAS_TB SET ID_ESTADO = 0
    WHERE ID_BENEFICIO = P_ID_BENEFICIO;
    
    UPDATE FIDE_BENEFICIOS_TB SET ID_ESTADO = 0
    WHERE ID_BENEFICIO = P_ID_BENEFICIO;
    
    COMMIT;
EXCEPTION 
 WHEN OTHERS THEN 
        RAISE_APPLICATION_ERROR(-20001, SQLERRM);
        
END FIDE_MEMBRESIAS_TB_ELIMINAR_BENEFICIO_SP;

PROCEDURE FIDE_MEMBRESIAS_TB_EDITAR_BENEFICIO (P_ID_BENEFICIO IN NUMBER, P_DESCRIPCION IN VARCHAR2) AS
BEGIN
    UPDATE FIDE_BENEFICIOS_TB SET DESCRIPCION = P_DESCRIPCION, ID_ESTADO = 1
    WHERE ID_BENEFICIO = P_ID_BENEFICIO;
    COMMIT;
EXCEPTION
 WHEN OTHERS THEN 
        RAISE_APPLICATION_ERROR(-20001, SQLERRM);
        

END FIDE_MEMBRESIAS_TB_EDITAR_BENEFICIO;

PROCEDURE FIDE_BENEFICIOS_TB_AGREGAR_SP (P_DESCRIPCION IN VARCHAR2) AS
BEGIN

    INSERT INTO FIDE_BENEFICIOS_TB (DESCRIPCION, ID_ESTADO) VALUES (P_DESCRIPCION, 1);
    COMMIT;

EXCEPTION
 WHEN OTHERS THEN 
        RAISE_APPLICATION_ERROR(-20001, SQLERRM);
END FIDE_BENEFICIOS_TB_AGREGAR_SP;


END FIDE_LOS_JAULES_MEMBRESIAS_PKG;



COMMIT;









COMMIT;

-----------------------------------
CREATE SEQUENCE ID_BENEFICIO_MEMBRESIA_SEQ INCREMENT BY 1 START WITH 1
MAXVALUE 99999 MINVALUE 0;

CREATE SEQUENCE ID_BENEFICIO_SEQ INCREMENT BY 1 START WITH 1
MAXVALUE 99999 MINVALUE 0;

create or replace TRIGGER FIDE_BENEFICIOS_MEMBRESIAS_TB_INSERTAR_TG
    BEFORE INSERT ON FIDE_BENEFICIOS_MEMBRESIAS_TB
    FOR EACH ROW
    BEGIN

        SELECT ID_BENEFICIO_MEMBRESIA_SEQ.NEXTVAL INTO :NEW.ID_BENEFICIO_MEMBRESIAS FROM DUAL;
END FIDE_BENEFICIOS_MEMBRESIAS_TB;

create or replace TRIGGER FIDE_BENEFICIOS_TB_INSERTAR_TG
    BEFORE INSERT ON FIDE_BENEFICIOS_TB
    FOR EACH ROW
    BEGIN

        SELECT ID_BENEFICIO_SEQ.NEXTVAL INTO :NEW.ID_BENEFICIO FROM DUAL;
END FIDE_BENEFICIOS_MEMBRESIAS_TB;


EXEC FIDE_LOS_JAULES_MEMBRESIAS_PKG.FIDE_TIPO_MEMBRESIAS_TB_ASOCIAR_BENEFICIOS_SP(1,2)



ALTER TABLE FIDE_MEMBRESIAS_TB ADD FECHA_ACTUALIZADA NUMBER(1) DEFAULT 0;