--CREACION DE PAQUETE PARA ALMACENAR TODO LO RELACIONADO A LAS MEMBRESIAS

CREATE OR REPLACE PACKAGE FIDE_LOS_JAULES_MEMBRESIAS_PKG 
AS
PROCEDURE FIDE_TIPO_MEMBRESIAS_TB_OBTENER_MEMBRESIAS_SP (P_CURSOR OUT SYS_REFCURSOR);
PROCEDURE FIDE_TIPO_MEMBRESIAS_TB_GET_MEMBRESIA_SP (P_CURSOR OUT SYS_REFCURSOR, P_ID IN NUMBER);
PROCEDURE FIDE_TIPO_MEMBRESIAS_TB_GET_BENEFICIOS_SP (P_CURSOR OUT SYS_REFCURSOR, P_ID IN NUMBER);
PROCEDURE FIDE_MEMBRESIAS_TB_GET_MEMBRESIA_USUARIO_SP (P_CURSOR OUT SYS_REFCURSOR, P_CEDULA IN NUMBER);
END FIDE_LOS_JAULES_MEMBRESIAS_PKG;

CREATE OR REPLACE PACKAGE BODY FIDE_LOS_JAULES_MEMBRESIAS_PKG  AS
--OBTENER LA MEMBRESIA DEL USUARIO
PROCEDURE FIDE_MEMBRESIAS_TB_GET_MEMBRESIA_USUARIO_SP (P_CURSOR OUT SYS_REFCURSOR, P_CEDULA IN NUMBER)
AS
BEGIN
    OPEN P_CURSOR FOR
    SELECT ID_MEMBRESIA, FECHA_INICIO, FECHA_FIN, ID_ESTADO, ID_TIPO_MEMBRESIA
    FROM FIDE_MEMBRESIAS_TB
    WHERE CEDULA = P_CEDULA AND ID_ESTADO = 1;

END FIDE_MEMBRESIAS_TB_GET_MEMBRESIA_USUARIO_SP;

---------------------------

PROCEDURE FIDE_TIPO_MEMBRESIAS_TB_OBTENER_MEMBRESIAS_SP (P_CURSOR OUT SYS_REFCURSOR)
IS
    V_CONTAR NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_CONTAR FROM FIDE_TIPO_MEMBRESIAS_TB WHERE ID_ESTADO = 1;
    IF V_CONTAR> 0 THEN
    OPEN P_CURSOR FOR
    SELECT ID_TIPO_MEMBRESIA, COSTO, DURACION_DIAS, NOMBRE, NUM_INVITADOS, DESCRIPCION
    FROM FIDE_TIPO_MEMBRESIAS_TB
    WHERE ID_ESTADO = 1;
    
    ELSE 
     OPEN p_cursor FOR
        SELECT 'No existen membresías disponibles' AS MENSAJE, NULL AS ID_TIPO_MEMBRESIA, NULL AS COSTO, NULL AS DURACION_DIAS, NULL AS NOMBRE, NULL AS NUM_INVITADOS FROM DUAL;
    END IF;
END FIDE_TIPO_MEMBRESIAS_TB_OBTENER_MEMBRESIAS_SP;


PROCEDURE FIDE_TIPO_MEMBRESIAS_TB_GET_MEMBRESIA_SP (P_CURSOR OUT SYS_REFCURSOR, P_ID IN NUMBER) 
AS
BEGIN
    OPEN P_CURSOR FOR 
    SELECT ID_TIPO_MEMBRESIA, COSTO, DURACION_DIAS, NOMBRE, NUM_INVITADOS, DESCRIPCION
    FROM FIDE_TIPO_MEMBRESIAS_TB
    WHERE ID_TIPO_MEMBRESIA = P_ID;
END FIDE_TIPO_MEMBRESIAS_TB_GET_MEMBRESIA_SP;

PROCEDURE FIDE_TIPO_MEMBRESIAS_TB_GET_BENEFICIOS_SP (P_CURSOR OUT SYS_REFCURSOR, P_ID IN NUMBER)
AS
BEGIN
    OPEN P_CURSOR FOR
    SELECT BM.ID_BENEFICIO_MEMBRESIAS, BM.ID_TIPO_MEMB, BM.ID_BENEFICIO, BM.ID_ESTADO, B.DESCRIPCION, M.NOMBRE
    FROM FIDE_BENEFICIOS_MEMBRESIAS_TB BM INNER JOIN FIDE_BENEFICIOS_TB B ON BM.ID_BENEFICIO = B.ID_BENEFICIO
    INNER JOIN FIDE_TIPO_MEMBRESIAS_TB M ON M.ID_TIPO_MEMBRESIA = BM.ID_TIPO_MEMB
    WHERE M.ID_TIPO_MEMBRESIA = P_ID AND BM.ID_ESTADO = 1;
END FIDE_TIPO_MEMBRESIAS_TB_GET_BENEFICIOS_SP;

END FIDE_LOS_JAULES_MEMBRESIAS_PKG;

COMMIT;