CREATE OR REPLACE PACKAGE FIDE_LOS_JAULES_RESERVAS_PKG AS
PROCEDURE FIDE_RESERVAS_TB_INSTALACIONES_SP (DATOS OUT SYS_REFCURSOR, P_TIPO IN NUMBER);
PROCEDURE FIDE_RESERVAS_TB_GET_INSTALACION_SP (DATOS OUT SYS_REFCURSOR, P_ID IN NUMBER);
END FIDE_LOS_JAULES_RESERVAS_PKG ;

CREATE OR REPLACE PACKAGE BODY FIDE_LOS_JAULES_RESERVAS_PKG AS
PROCEDURE FIDE_RESERVAS_TB_INSTALACIONES_SP (DATOS OUT SYS_REFCURSOR, P_TIPO IN NUMBER)
AS
BEGIN  
    OPEN DATOS FOR
    SELECT I.ID_INSTALACION, I.NOMBRE, I.COSTO, I.ID_TIPO_INSTALACION, I.CAPACIDAD, T.DESCRIPCION
    FROM FIDE_INSTALACIONES_TB I INNER JOIN FIDE_TIPO_INSTALACION_TB T
    ON I.ID_TIPO_INSTALACION = T.ID_TIPO_INSTALACION
    WHERE I.ID_ESTADO = 1 AND I.ID_TIPO_INSTALACION = P_TIPO;
END FIDE_RESERVAS_TB_INSTALACIONES_SP;

PROCEDURE FIDE_RESERVAS_TB_GET_INSTALACION_SP (DATOS OUT SYS_REFCURSOR, P_ID IN NUMBER)
AS
BEGIN
    OPEN DATOS FOR
     SELECT I.ID_INSTALACION, I.NOMBRE, I.COSTO, I.ID_TIPO_INSTALACION, I.CAPACIDAD, T.DESCRIPCION
    FROM FIDE_INSTALACIONES_TB I INNER JOIN FIDE_TIPO_INSTALACION_TB T
    ON I.ID_TIPO_INSTALACION = T.ID_TIPO_INSTALACION
    WHERE I.ID_INSTALACION = P_ID;
END FIDE_RESERVAS_TB_GET_INSTALACION_SP;
END FIDE_LOS_JAULES_RESERVAS_PKG ;
