CREATE OR REPLACE PACKAGE FIDE_LOS_JAULES_EVENTOS_PKG AS
PROCEDURE FIDE_EVENTOS_TB_GET_EVENTOS_ACTIVOS_SP (DATOS OUT SYS_REFCURSOR);
PROCEDURE FIDE_EVENTOS_TB_GET_EVENTO_SP (DATOS OUT SYS_REFCURSOR, P_ID IN NUMBER);
PROCEDURE FIDE_EVENTOS_TB_INSERTAR_REGISTRO_SP (P_CEDULA IN NUMBER, P_ID_INVITADO IN NUMBER, P_ID_EVENTO IN NUMBER, P_FECHA_REGISTRO IN DATE);
END FIDE_LOS_JAULES_EVENTOS_PKG;

CREATE OR REPLACE PACKAGE BODY FIDE_LOS_JAULES_EVENTOS_PKG AS

PROCEDURE FIDE_EVENTOS_TB_GET_EVENTOS_ACTIVOS_SP (DATOS OUT SYS_REFCURSOR) 
AS
BEGIN
    OPEN DATOS FOR
    SELECT E.ID_EVENTO, E.NOMBRE, E.DESCRIPCION,TO_CHAR(hora, 'HH:MI AM') AS HORA, E.FECHA, E.ID_ESTADO, E.ID_INSTALACION, E.CAPACIDAD, I.NOMBRE AS INSTALACION
    FROM FIDE_EVENTOS_TB E
    INNER JOIN FIDE_INSTALACIONES_TB I
    ON E.ID_INSTALACION = I.ID_INSTALACION
    WHERE E.ID_ESTADO = 1;
END FIDE_EVENTOS_TB_GET_EVENTOS_ACTIVOS_SP;


PROCEDURE FIDE_EVENTOS_TB_GET_EVENTO_SP (DATOS OUT SYS_REFCURSOR, P_ID IN NUMBER) 
AS
BEGIN
    OPEN DATOS FOR
    SELECT E.ID_EVENTO, E.NOMBRE, E.DESCRIPCION, E.HORA, E.FECHA, E.ID_ESTADO, E.ID_INSTALACION, E.CAPACIDAD, I.NOMBRE AS INSTALACION
    FROM FIDE_EVENTOS_TB E
    INNER JOIN FIDE_INSTALACIONES_TB I
    ON E.ID_INSTALACION = I.ID_INSTALACION
    WHERE E.ID_EVENTO = P_ID;
END FIDE_EVENTOS_TB_GET_EVENTO_SP;


    
PROCEDURE FIDE_EVENTOS_TB_INSERTAR_REGISTRO_SP (P_CEDULA IN NUMBER, P_ID_INVITADO IN NUMBER, P_ID_EVENTO IN NUMBER, P_FECHA_REGISTRO IN DATE) AS
V_SQL VARCHAR2(500);
BEGIN
    V_SQL := 'INSERT INTO FIDE_REGISTRO_EVENTOS_TB (CEDULA, ID_INVITADO, ID_EVENTO, FECHA_REGISTRO) VALUES (:1,:2,:3,:4)';
    EXECUTE IMMEDIATE V_SQL USING P_CEDULA, P_ID_INVITADO, P_ID_EVENTO, P_FECHA_REGISTRO;
    COMMIT;
END FIDE_EVENTOS_TB_INSERTAR_REGISTRO_SP;

END FIDE_LOS_JAULES_EVENTOS_PKG;



