CREATE OR REPLACE PACKAGE FIDE_LOS_JAULES_USUARIOS_PKG AS
PROCEDURE FIDE_USUARIOS_TB_GET_USERS_SP (DATOS OUT SYS_REFCURSOR);
END;

create or replace PACKAGE BODY FIDE_LOS_JAULES_USUARIOS_PKG AS

PROCEDURE FIDE_USUARIOS_TB_GET_USERS_SP (DATOS OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN DATOS FOR
    SELECT U.CEDULA, U.NOMBRE || ' ' ||  U.APELLIDO1 || ' ' || U.APELLIDO2 as NOMBRE, U.FECHA_INGRESO, U.FECHA_BAJA, R.DESCRIPCION AS ROL, E.DESCRIPCION AS ESTADO, EM.EMAIL
    FROM FIDE_USUARIOS_TB U
    INNER JOIN FIDE_ROLES_TB R ON U.ID_ROL = R.ID_ROL
    INNER JOIN FIDE_ESTADO_TB E ON U.ID_ESTADO = E.ID_ESTADO
    LEFT JOIN FIDE_EMAIL_TB EM ON U.CEDULA = EM.CEDULA;
END FIDE_USUARIOS_TB_GET_USERS_SP;

END FIDE_LOS_JAULES_USUARIOS_PKG;