-- CABECERA DEL PAQUETE
CREATE OR REPLACE PACKAGE FIDE_LOS_JAULES_USUARIOS_PKG AS
  PROCEDURE FIDE_USUARIOS_TB_GET_USERS_SP (DATOS OUT SYS_REFCURSOR);
  PROCEDURE FIDE_USUARIO_TB_GET_BY_USUARIO_SP (p_usuario IN VARCHAR2, datos OUT SYS_REFCURSOR);
  PROCEDURE FIDE_USUARIO_TB_GET_BY_CEDULA_SP (p_cedula IN VARCHAR2, datos OUT SYS_REFCURSOR);
  PROCEDURE FIDE_USUARIO_TB_ELIMINAR_SP (p_cedula IN VARCHAR2);
  PROCEDURE FIDE_USUARIO_TB_MODIFICAR_SP (p_cedula IN NUMBER, p_nombre IN VARCHAR2, p_apellido1 IN VARCHAR2, p_apellido2 IN VARCHAR2, p_email IN VARCHAR2, p_id_rol IN NUMBER
);

END FIDE_LOS_JAULES_USUARIOS_PKG;
/


-- CUERPO DEL PAQUETE
CREATE OR REPLACE PACKAGE BODY FIDE_LOS_JAULES_USUARIOS_PKG AS

  PROCEDURE FIDE_USUARIOS_TB_GET_USERS_SP (DATOS OUT SYS_REFCURSOR) AS
  BEGIN
    OPEN DATOS FOR
      SELECT 
          U.CEDULA, 
          U.NOMBRE,
          U.APELLIDO1,
          U.APELLIDO2,
          U.FECHA_INGRESO, 
          U.FECHA_BAJA, 
          R.DESCRIPCION AS ROL, 
          E.DESCRIPCION AS ESTADO, 
          EM.EMAIL,
          U.USUARIO  -- Se agrega el campo USUARIO
      FROM FIDE_USUARIOS_TB U
      INNER JOIN FIDE_ROLES_TB R ON U.ID_ROL = R.ID_ROL
      INNER JOIN FIDE_ESTADO_TB E ON U.ID_ESTADO = E.ID_ESTADO
      LEFT JOIN FIDE_EMAIL_TB EM ON U.CEDULA = EM.CEDULA
      WHERE U.ID_ESTADO = 1;
  END;

  PROCEDURE FIDE_USUARIO_TB_GET_BY_USUARIO_SP (p_usuario IN VARCHAR2, datos OUT SYS_REFCURSOR) AS
  BEGIN
    OPEN datos FOR
      SELECT 
        U.CEDULA,
        U.NOMBRE,
        U.APELLIDO1,
        U.APELLIDO2,
        U.USUARIO,
        U.FECHA_INGRESO,
        U.FECHA_BAJA,
        R.DESCRIPCION AS ROL,
        E.DESCRIPCION AS ESTADO,
        EM.EMAIL
      FROM FIDE_USUARIOS_TB U
      INNER JOIN FIDE_ROLES_TB R ON U.ID_ROL = R.ID_ROL
      INNER JOIN FIDE_ESTADO_TB E ON U.ID_ESTADO = E.ID_ESTADO
      LEFT JOIN FIDE_EMAIL_TB EM ON U.CEDULA = EM.CEDULA
      WHERE U.USUARIO = p_usuario;
  END;

  PROCEDURE FIDE_USUARIO_TB_GET_BY_CEDULA_SP (p_cedula IN VARCHAR2, datos OUT SYS_REFCURSOR) AS
  BEGIN
    OPEN datos FOR
      SELECT 
        U.CEDULA, 
        U.NOMBRE, 
        U.APELLIDO1, 
        U.APELLIDO2, 
        EM.EMAIL,
        U.USUARIO,
        R.DESCRIPCION AS ROL, 
        E.DESCRIPCION AS ESTADO
      FROM FIDE_USUARIOS_TB U
      INNER JOIN FIDE_ROLES_TB R ON U.ID_ROL = R.ID_ROL
      INNER JOIN FIDE_ESTADO_TB E ON U.ID_ESTADO = E.ID_ESTADO
      LEFT JOIN FIDE_EMAIL_TB EM ON U.CEDULA = EM.CEDULA
      WHERE U.CEDULA = p_cedula;
  END;

  PROCEDURE FIDE_USUARIO_TB_ELIMINAR_SP (p_cedula IN VARCHAR2) AS
  BEGIN
    UPDATE FIDE_USUARIOS_TB SET ID_ESTADO = 2 WHERE CEDULA = p_cedula;
    COMMIT;
  END;
  
    PROCEDURE FIDE_USUARIO_TB_MODIFICAR_SP (
      p_cedula        IN NUMBER,
      p_nombre        IN VARCHAR2,
      p_apellido1     IN VARCHAR2,
      p_apellido2     IN VARCHAR2,
      p_email         IN VARCHAR2,
      p_id_rol     IN NUMBER
    ) AS
    BEGIN
      UPDATE FIDE_USUARIOS_TB
      SET 
        NOMBRE        = p_nombre,
        APELLIDO1     = p_apellido1,
        APELLIDO2     = p_apellido2,
        ID_ROL        = p_id_rol
      WHERE CEDULA = p_cedula;
    
      MERGE INTO FIDE_EMAIL_TB EM
      USING (SELECT p_cedula AS CEDULA FROM DUAL) SRC
      ON (EM.CEDULA = SRC.CEDULA)
      WHEN MATCHED THEN
        UPDATE SET EM.EMAIL = p_email
      WHEN NOT MATCHED THEN
        INSERT (ID_EMAIL, CEDULA, EMAIL)
        VALUES (FIDE_EMAIL_SEQ.NEXTVAL, p_cedula, p_email);
    
      COMMIT;
    END;


END FIDE_LOS_JAULES_USUARIOS_PKG;
