--PACKAGE CREADO PARA GERSTIONAR LA INFORMACION DE LOS PROVEEDORES
CREATE OR REPLACE PACKAGE FIDE_LOS_JAULES_PROVEEDORES_PKG AS
    PROCEDURE FIDE_PROVEEDORES_TB_GET_PROVEEDORES_SP (DATOS OUT SYS_REFCURSOR);
    PROCEDURE FIDE_PROVEEDORES_TB_GET_PROVEEDOR_SP (DATOS OUT SYS_REFCURSOR, P_ID IN NUMBER);
    
    PROCEDURE FIDE_PROVEEDORES_TB_INSERTAR_SP (
        P_ID_PROVEEDOR IN NUMBER,
        P_ID_ESTADO IN NUMBER,
        P_NOMBRE IN VARCHAR2,
        P_TELEFONO IN NUMBER,
        P_EMAIL IN VARCHAR2
    );
    
    PROCEDURE FIDE_PROVEEDORES_TB_ACTUALIZAR_SP (
        P_ID_PROVEEDOR IN NUMBER,
        P_ID_ESTADO IN NUMBER,
        P_NOMBRE IN VARCHAR2,
        P_TELEFONO IN NUMBER,
        P_EMAIL IN VARCHAR2
    );
    
    PROCEDURE FIDE_PROVEEDORES_TB_ELIMINAR_SP (
        P_ID_PROVEEDOR IN NUMBER
    );
END FIDE_LOS_JAULES_PROVEEDORES_PKG;
/

-- Ahora el cuerpo del paquete
CREATE OR REPLACE PACKAGE BODY FIDE_LOS_JAULES_PROVEEDORES_PKG AS

    PROCEDURE FIDE_PROVEEDORES_TB_GET_PROVEEDORES_SP (DATOS OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN DATOS FOR
        SELECT 
            P.ID_PROVEEDOR,
            P.NOMBRE,
            P.TELEFONO,
            P.EMAIL,
            P.ID_ESTADO,
            E.DESCRIPCION AS ESTADO  -- Cambié NOMBRE por DESCRIPCION
        FROM FIDE_PROVEEDORES_TB P
        JOIN FIDE_ESTADO_TB E ON P.ID_ESTADO = E.ID_ESTADO;
    END;

    PROCEDURE FIDE_PROVEEDORES_TB_GET_PROVEEDOR_SP (DATOS OUT SYS_REFCURSOR, P_ID IN NUMBER) IS
    BEGIN
        OPEN DATOS FOR
        SELECT 
            P.ID_PROVEEDOR,
            P.NOMBRE,
            P.TELEFONO,
            P.EMAIL,
            P.ID_ESTADO,
            E.DESCRIPCION AS ESTADO  -- Cambié NOMBRE por DESCRIPCION
        FROM FIDE_PROVEEDORES_TB P
        JOIN FIDE_ESTADO_TB E ON P.ID_ESTADO = E.ID_ESTADO
        WHERE P.ID_PROVEEDOR = P_ID;
    END;

    PROCEDURE FIDE_PROVEEDORES_TB_INSERTAR_SP (
        P_ID_PROVEEDOR IN NUMBER,
        P_ID_ESTADO IN NUMBER,
        P_NOMBRE IN VARCHAR2,
        P_TELEFONO IN NUMBER,
        P_EMAIL IN VARCHAR2
    ) IS
    BEGIN
        INSERT INTO FIDE_PROVEEDORES_TB (
            ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL
        ) VALUES (
            P_ID_PROVEEDOR, P_ID_ESTADO, P_NOMBRE, P_TELEFONO, P_EMAIL
        );
        COMMIT;
    END;

    PROCEDURE FIDE_PROVEEDORES_TB_ACTUALIZAR_SP (
        P_ID_PROVEEDOR IN NUMBER,
        P_ID_ESTADO IN NUMBER,
        P_NOMBRE IN VARCHAR2,
        P_TELEFONO IN NUMBER,
        P_EMAIL IN VARCHAR2
    ) IS
    BEGIN
        UPDATE FIDE_PROVEEDORES_TB
        SET 
            ID_ESTADO = P_ID_ESTADO,
            NOMBRE = P_NOMBRE,
            TELEFONO = P_TELEFONO,
            EMAIL = P_EMAIL
        WHERE ID_PROVEEDOR = P_ID_PROVEEDOR;
        COMMIT;
    END;

    PROCEDURE FIDE_PROVEEDORES_TB_ELIMINAR_SP (
        P_ID_PROVEEDOR IN NUMBER
    ) IS
    BEGIN
        DELETE FROM FIDE_PROVEEDORES_TB
        WHERE ID_PROVEEDOR = P_ID_PROVEEDOR;
        COMMIT;
    END;

-- Asegúrate de poner este END con el nombre del paquete
END FIDE_LOS_JAULES_PROVEEDORES_PKG;
/



