-------------------------PUNTO 1-----------------------------------
---------CREACION DE USUARIO Y GRANTS BASICOS----------------------
CREATE USER Administrator Identified by Admin123;
GRANT CREATE SESSION TO Administrator;
GRANT CONNECT TO ADMINISTRATOR;
GRANT RESOURCE TO ADMINISTRATOR;
-------------------------PUNTO 2-----------------------------------
---------------------CREACION DE TABLE SPACE Y ASIGNACION-------------------------------
CREATE TABLESPACE FIDE_LOS_JAULES_TBS
DATAFILE 'C:\bd\19c\oradata\ORCL\FIDE_LOS_JAULES_TBS.DBF'
SIZE 300M
AUTOEXTEND ON
NEXT 30M
MAXSIZE 3G; 
COMMIT;  

ALTER USER ADMINISTRATOR QUOTA UNLIMITED ON FIDE_LOS_JAULES_TBS;
ALTER USER ADMINISTRATOR DEFAULT TABLESPACE FIDE_LOS_JAULES_TBS;
-------------------------PUNTO 3-----------------------------------
---------------------CREACION DE TABLA PARTICIONADA-------------------------------
------------------------TABLA EVENTOS----------------------------------
CREATE TABLE ADMINISTRATOR.FIDE_EVENTOS_TB (
  ID_EVENTO       NUMBER,
  NOMBRE          VARCHAR2(50),
  DESCRIPCION     VARCHAR2(100),
  HORA            TIMESTAMP(6),
  FECHA           DATE,
  ID_ESTADO       NUMBER,
  ID_INSTALACION  NUMBER,
  CAPACIDAD       NUMBER
)
TABLESPACE FIDE_LOS_JAULES_TBS ------------------PUNTO 7 / TABLA ASOCIADA A TABBLE SPACE------------------------
PARTITION BY RANGE (FECHA) (
  PARTITION P_2021 VALUES LESS THAN (TO_DATE('2022-01-01', 'YYYY-MM-DD')),
  PARTITION P_2022 VALUES LESS THAN (TO_DATE('2023-01-01', 'YYYY-MM-DD')),
  PARTITION P_2023 VALUES LESS THAN (TO_DATE('2024-01-01', 'YYYY-MM-DD')),
  PARTITION P_2024 VALUES LESS THAN (TO_DATE('2025-01-01', 'YYYY-MM-DD')),
  PARTITION P_2025 VALUES LESS THAN (TO_DATE('2026-01-01', 'YYYY-MM-DD'))
);
------------------------TABLA FACTURA----------------------------------
CREATE TABLE ADMINISTRATOR.FIDE_FACTURA_TB (
  ID_FACTURA     NUMBER,
  ID_ORDEN       NUMBER,
  FECHA_EMISION  DATE,
  SUBTOTAL       NUMBER(10,2),
  TOTAL          NUMBER(10,2),
  IVA            NUMBER(10,2)
)
TABLESPACE FIDE_LOS_JAULES_TBS ------------------PUNTO 7 / TABLA ASOCIADA A TABBLE SPACE------------------------
PARTITION BY RANGE (FECHA_EMISION) (
  PARTITION P_2021 VALUES LESS THAN (TO_DATE('2022-01-01', 'YYYY-MM-DD')),
  PARTITION P_2022 VALUES LESS THAN (TO_DATE('2023-01-01', 'YYYY-MM-DD')),
  PARTITION P_2023 VALUES LESS THAN (TO_DATE('2024-01-01', 'YYYY-MM-DD')),
  PARTITION P_2024 VALUES LESS THAN (TO_DATE('2025-01-01', 'YYYY-MM-DD')),
  PARTITION P_2025 VALUES LESS THAN (TO_DATE('2026-01-01', 'YYYY-MM-DD'))
);
-------------------------PUNTO 4-----------------------------------
---------------------CREACION DE PROFILE-------------------------------
CREATE PROFILE FIDE_LOS_JAULES_PROF LIMIT
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LIFE_TIME 90 --PASSWORD EXPIRA EN 90 DIAS
    PASSWORD_LOCK_TIME 1/24 --SE BLOQUEA EL USUARIO POR 1 HORA POR INTENTOS FALLIDOS, MEJORA LA SEGURIDAD
    SESSIONS_PER_USER 3
    IDLE_TIME 30 --CIERRA SESION DESPUES DE 30 MINUTOS DE INACTIVIDAD
    PASSWORD_VERIFY_FUNCTION FIDE_VERIFICA_CONTRASENA;

ALTER USER ADMINISTRATOR 
PROFILE FIDE_LOS_JAULES_PROF;
-------------------------PUNTO 5-----------------------------------
--------------------ROL---------------------------------------
CREATE ROLE ADMIN_ROL;

GRANT CREATE SESSION TO ADMIN_ROL;       
GRANT CREATE TABLE TO ADMIN_ROL;         
GRANT CREATE VIEW TO ADMIN_ROL;          
GRANT CREATE PROCEDURE TO ADMIN_ROL;     
GRANT CREATE SEQUENCE TO ADMIN_ROL;      
GRANT CREATE ANY TABLE TO ADMIN_ROL;     
GRANT ALTER ANY TABLE TO ADMIN_ROL;      
GRANT DROP ANY TABLE TO ADMIN_ROL;       
GRANT CREATE TABLESPACE TO ADMIN_ROL;
GRANT CREATE PROFILE TO ADMIN_ROL;
GRANT SELECT ANY TABLE TO ADMIN_ROL;     
GRANT UPDATE ANY TABLE TO ADMIN_ROL;     
GRANT ALTER ANY TABLE TO ADMIN_ROL;
GRANT EXECUTE ANY PROCEDURE TO ADMIN_ROL;

GRANT ADMIN_ROL TO ADMINISTRATOR;

-------------------------PUNTO 6-----------------------------------
--------------MOSTRAR NOMENCLATURA EN BASE DE DATOS--------------

-------------------------PUNTO 8-----------------------------------
---------------MOSTRAR DAHSBOARD DEL BI----------------------------

-------------------------PUNTO 9-----------------------------------
------VISTA GENERAL DE FUNCIONALIDADES WEB COMO CLIENTE Y ADMIN----
