-- =========================
-- PUNTO 1: CREACIÓN DE USUARIO Y GRANTS BÁSICOS
-- =========================
CREATE USER ADMINISTRATOR IDENTIFIED BY Admin123;

GRANT CREATE SESSION TO ADMINISTRATOR;
GRANT CONNECT         TO ADMINISTRATOR;
GRANT RESOURCE        TO ADMINISTRATOR;

CREATE USER FIDE_LOS_JAULES_CLIENTE IDENTIFIED BY 123 DEFAULT TABLESPACE FIDE_LOS_JAULES_TBS;
GRANT CONNECT TO FIDE_LOS_JAULES_CLIENTE_ROLE;


-- =========================
-- PUNTO 2: CREACIÓN DE TABLESPACE Y ASIGNACIÓN
-- =========================
CREATE TABLESPACE FIDE_LOS_JAULES_TBS
    DATAFILE 'C:\bd\19c\oradata\ORCL\FIDE_LOS_JAULES_TBS.DBF'
    SIZE 300M
    AUTOEXTEND ON
    NEXT 30M
    MAXSIZE 3G;

COMMIT;

ALTER USER ADMINISTRATOR QUOTA UNLIMITED ON FIDE_LOS_JAULES_TBS;
ALTER USER ADMINISTRATOR DEFAULT TABLESPACE FIDE_LOS_JAULES_TBS;


-- =========================
-- PUNTO 3: CREACIÓN DE TABLAS PARTICIONADAS
-- =========================

-- Tabla: EVENTOS
CREATE TABLE ADMINISTRATOR.FIDE_EVENTOS_TB (
    ID_EVENTO       NUMBER,
    NOMBRE          VARCHAR2(50),
    DESCRIPCION     VARCHAR2(100),
    HORA            TIMESTAMP(6),
    FECHA           DATE,
    ID_ESTADO       NUMBER,
    ID_INSTALACION  NUMBER,
    CAPACIDAD       NUMBER
)
TABLESPACE FIDE_LOS_JAULES_TBS
PARTITION BY RANGE (FECHA) (
    PARTITION P_2021 VALUES LESS THAN (TO_DATE('2022-01-01', 'YYYY-MM-DD')),
    PARTITION P_2022 VALUES LESS THAN (TO_DATE('2023-01-01', 'YYYY-MM-DD')),
    PARTITION P_2023 VALUES LESS THAN (TO_DATE('2024-01-01', 'YYYY-MM-DD')),
    PARTITION P_2024 VALUES LESS THAN (TO_DATE('2025-01-01', 'YYYY-MM-DD')),
    PARTITION P_2025 VALUES LESS THAN (TO_DATE('2026-01-01', 'YYYY-MM-DD'))
);

-- Tabla: FACTURA
CREATE TABLE ADMINISTRATOR.FIDE_FACTURA_TB (
    ID_FACTURA     NUMBER,
    ID_ORDEN       NUMBER,
    FECHA_EMISION  DATE,
    SUBTOTAL       NUMBER(10,2),
    TOTAL          NUMBER(10,2),
    IVA            NUMBER(10,2)
)
TABLESPACE FIDE_LOS_JAULES_TBS
PARTITION BY RANGE (FECHA_EMISION) (
    PARTITION P_2021 VALUES LESS THAN (TO_DATE('2022-01-01', 'YYYY-MM-DD')),
    PARTITION P_2022 VALUES LESS THAN (TO_DATE('2023-01-01', 'YYYY-MM-DD')),
    PARTITION P_2023 VALUES LESS THAN (TO_DATE('2024-01-01', 'YYYY-MM-DD')),
    PARTITION P_2024 VALUES LESS THAN (TO_DATE('2025-01-01', 'YYYY-MM-DD')),
    PARTITION P_2025 VALUES LESS THAN (TO_DATE('2026-01-01', 'YYYY-MM-DD'))
);


-- =========================
-- PUNTO 4: CREACIÓN DE PROFILE
-- =========================
CREATE PROFILE FIDE_LOS_JAULES_PROF LIMIT
    FAILED_LOGIN_ATTEMPTS     3
    PASSWORD_LIFE_TIME        90          
    PASSWORD_LOCK_TIME        1/24        
    SESSIONS_PER_USER         3
    IDLE_TIME                 30          
    PASSWORD_VERIFY_FUNCTION  FIDE_VERIFICA_CONTRASENA;

ALTER USER ADMINISTRATOR PROFILE FIDE_LOS_JAULES_PROF;


-- =========================
-- PUNTO 5: CREACIÓN DE ROL
-- =========================
CREATE ROLE ADMIN_ROL;

GRANT CREATE SESSION        TO ADMIN_ROL;
GRANT CREATE TABLE          TO ADMIN_ROL;
GRANT CREATE VIEW           TO ADMIN_ROL;
GRANT CREATE PROCEDURE      TO ADMIN_ROL;
GRANT CREATE SEQUENCE       TO ADMIN_ROL;
GRANT CREATE ANY TABLE      TO ADMIN_ROL;
GRANT ALTER ANY TABLE       TO ADMIN_ROL;
GRANT DROP ANY TABLE        TO ADMIN_ROL;
GRANT CREATE TABLESPACE     TO ADMIN_ROL;
GRANT CREATE PROFILE        TO ADMIN_ROL;
GRANT SELECT ANY TABLE      TO ADMIN_ROL;
GRANT UPDATE ANY TABLE      TO ADMIN_ROL;
GRANT EXECUTE ANY PROCEDURE TO ADMIN_ROL;

GRANT ADMIN_ROL TO ADMINISTRATOR;

CREATE ROLE FIDE_LOS_JAULES_CLIENTE_ROLE;

GRANT SELECT ON ADMINISTRATOR.FIDE_ASOCIADO_TB TO                       FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_BENEFICIOS_MEMBRESIAS_TB TO          FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_BENEFICIOS_TB TO                     FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_CANTONES_TB TO                       FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_CARGO_TB TO                          FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_CARRITO_ITEMS_TB TO                  FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_CARRITO_TB TO                        FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_CLAVE_ENCRIPTAR_TB TO                FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_DIRECCIONES_TB TO                    FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_DISTRITOS_TB TO                      FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_EMAIL_TB TO                          FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_ESTADO_TB TO                         FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_EVENTOS_TB TO                        FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_FACTURA_TB TO                        FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_INVENTARIO_TB TO                     FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_INSTALACIONES_TB TO                  FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_INVITADOS_TB TO                      FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_MEMBRESIAS_TB TO                     FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_METODO_PAGO_TB TO                    FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_ORDEN_ITEMS_TB TO                    FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_ORDENES_TB TO                        FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_PRODUCTOS_PROVEEDOR_TB TO            FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_PRODUCTOS_TB TO                      FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_PROVEEDORES_TB TO                    FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_PROVINCIAS_TB TO                     FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_REGISTRO_EVENTOS_TB TO               FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_RESERVAS_TB TO                       FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_ROLES_TB TO                          FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_SERVICIOS_PROVEEDOR_TB TO            FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_SERVICIOS_TB TO                      FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_TELEFONOS_TB TO                      FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_TIPO_INSTALACION_TB TO               FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_TIPO_MEMBRESIAS_TB TO                FIDE_LOS_JAULES_CLIENTE_ROLE;
GRANT SELECT ON ADMINISTRATOR.FIDE_USUARIOS_TB TO                       FIDE_LOS_JAULES_CLIENTE_ROLE;

GRANT FIDE_LOS_JAULES_CLIENTE_ROLE TO FIDE_LOS_JAULES_CLIENTE;
-- =========================
-- PUNTO 6: MOSTRAR NOMENCLATURA EN BASE DE DATOS
-- =========================

-- =========================
-- PUNTO 7: (Ya integrado en la definición de tablas con TABLESPACE)
-- =========================

-- =========================
-- PUNTO 8: MOSTRAR DASHBOARD DEL BI
-- =========================

-- =========================
-- PUNTO 9: VISTA GENERAL DE FUNCIONALIDADES WEB COMO CLIENTE Y ADMIN
-- =========================

-- =========================
-- PUNTO 10: AUDITORIA DE LA BD (EXTRAS)
-- =========================

AUDIT ALL BY ADMINISTRATOR BY ACCESS; 
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_ASOCIADO_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_BENEFICIOS_MEMBRESIAS_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_CANTONES_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_CARGO_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_CARRITO_ITEMS_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_CARRITO_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_CLAVE_ENCRIPTAR_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_DIRECCIONES_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_DISTRITOS_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_EMAIL_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_ESTADO_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_EVENTOS_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_FACTURA_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_INSTALACIONES_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_INVENTARIO_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_INVITADOS_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_MEMBRESIAS_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_METODO_PAGO_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_ORDEN_ITEMS_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_ORDENES_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_PRODUCTOS_PROVEEDOR_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_PRODUCTOS_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_PROVEEDORES_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_PROVINCIAS_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_REGISTRO_EVENTOS_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_RESERVAS_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_ROLES_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_SERVICIOS_PROVEEDOR_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_SERVICIOS_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_TELEFONOS_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_TIPO_INSTALACION_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_TIPO_MEMBRESIAS_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMINISTRATOR.FIDE_USUARIOS_TB BY ACCESS;
