--CREACION DE SECUENIAS Y TRIGGERS

CREATE SEQUENCE ID_REGISTRO_SEQ START WITH 1 INCREMENT BY 1;
COMMIT;

CREATE OR REPLACE TRIGGER FIDE_REGISTRO_EVENTOS_TB_INSERTAR_TG
    BEFORE INSERT ON FIDE_REGISTRO_EVENTOS_TB
    FOR EACH ROW
    BEGIN
        
        SELECT ID_REGISTRO_SEQ.NEXTVAL INTO :NEW.ID_REGISTRO FROM DUAL;
END FIDE_REGISTRO_EVENTOS_TB_INSERTAR_TG;


--CREACION DE TRIGGER QUE VALIDA QUE ANTES DE UN REGISTRO EN EVENTOS EL USUARIO LOGUEADO TENGA UNA MEMBRESIA O UN PASE PARA LA FECHA DEL EVENTO
create or replace TRIGGER FIDE_REGISTRO_EVENTOS_TB_VALIDAR_MEMBRESIAS_TB
BEFORE INSERT ON FIDE_REGISTRO_EVENTOS_TB
FOR EACH ROW
DECLARE
    V_MEMBRESIA_VALIDA NUMBER;
    V_FECHA_EVENTO DATE;
BEGIN
    -- Obtener la fecha del evento desde la tabla FIDE_EVENTOS_TB
    SELECT FECHA INTO V_FECHA_EVENTO
    FROM FIDE_EVENTOS_TB
    WHERE ID_EVENTO = :NEW.ID_EVENTO;

    -- Verificar si el usuario tiene una membresía válida para la fecha del evento
    SELECT COUNT(*) INTO V_MEMBRESIA_VALIDA
    FROM FIDE_MEMBRESIAS_TB 
    WHERE CEDULA = :NEW.CEDULA 
    AND ID_ESTADO = 1  -- Estado activo
    AND V_FECHA_EVENTO BETWEEN FECHA_INICIO AND FECHA_FIN;

    -- Si no tiene una membresía válida, lanzar un error
    IF V_MEMBRESIA_VALIDA=1 THEN
        RAISE_APPLICATION_ERROR(-20001, 'El usuario no tiene una membresía o pase activo para validar el registro al evento');
    END IF;
END;

commit;


---SECUENCIA DE CREACION DE CARRITO
CREATE SEQUENCE ID_CARRITO_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FIDE_CARRITO_TB_INSERTAR_TG
    BEFORE INSERT ON FIDE_CARRITO_TB
    FOR EACH ROW
    BEGIN
        
        SELECT ID_CARRITO_SEQ.NEXTVAL INTO :NEW.ID_CARRITO FROM DUAL;
END FIDE_CARRITO_TB_INSERTAR_TG;

--SECUENCIA CREACION DE ITEMS CARRITO

CREATE SEQUENCE ID_CARRITO_ITEM_SEQ START WITH 1 INCREMENT BY 1;

-- Crear el trigger para asignar automáticamente el ID_CARRITO
CREATE OR REPLACE TRIGGER FIDE_CARRITO_ITEMS_TB_INSERTAR_TG
BEFORE INSERT ON FIDE_CARRITO_ITEMS_TB
FOR EACH ROW
BEGIN
    SELECT ID_CARRITO_ITEM_SEQ.NEXTVAL INTO :NEW.ID_ITEM FROM DUAL;
END;

--TRIGGER PARA LAS RESERVAS

CREATE SEQUENCE ID_RESERVA_SEQ START WITH 1 INCREMENT BY 1;
COMMIT;

CREATE OR REPLACE TRIGGER FIDE_RESERVAS_TB_INSERTAR_TG
    BEFORE INSERT ON FIDE_RESERVAS_TB
    FOR EACH ROW
    BEGIN  
        SELECT ID_RESERVA_SEQ.NEXTVAL INTO :NEW.ID_RESERVA FROM DUAL;
END FIDE_RESERVAS_TB_INSERTAR_TG;

CREATE OR REPLACE TRIGGER FIDE_CARRITO_TB_VALIDAR_MEMBRESIA_TG
BEFORE INSERT ON FIDE_CARRITO_ITEMS_TB
FOR EACH ROW
DECLARE
    V_CONTAR NUMBER;
BEGIN
    -- Solo ejecutar la validación si se está insertando una membresía
    IF :NEW.ID_TIPO_MEMBRESIA IS NOT NULL THEN
        SELECT COUNT(ID_TIPO_MEMBRESIA)
        INTO V_CONTAR
        FROM FIDE_CARRITO_ITEMS_TB
        WHERE ID_CARRITO = :NEW.ID_CARRITO
        AND ID_TIPO_MEMBRESIA IS NOT NULL;

        IF V_CONTAR > 0 THEN
            RAISE_APPLICATION_ERROR(-20001, 'El carrito ya contiene una membresía. Solo puede haber una a la vez.');
        END IF;
    END IF;
END;

CREATE SEQUENCE ID_ORDEN_SEQ START WITH 1 INCREMENT BY 1;
COMMIT;

--CREACION DE TRIGGER PARA LA CREACION DE ORDENES


CREATE SEQUENCE ID_ORDEN_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FIDE_ORDENES_TB_INSERTAR_TG
    BEFORE INSERT ON FIDE_ORDENES_TB
    FOR EACH ROW
    BEGIN
        
        SELECT ID_ORDEN_SEQ.NEXTVAL INTO :NEW.ID_ORDEN FROM DUAL;
END FIDE_ORDENES_TB_INSERTAR_TG;

--CREACION DE TRIGGER PARA LA CREACION DE ORDENES


CREATE SEQUENCE ID_ORDEN_ITEM_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FIDE_ORDEN_ITEMS_TB_INSERTAR_TG
    BEFORE INSERT ON FIDE_ORDEN_ITEMS_TB
    FOR EACH ROW
    BEGIN
        
        SELECT ID_ORDEN_ITEM_SEQ.NEXTVAL INTO :NEW.ID_ORDEN_ITEM FROM DUAL;
END FIDE_ORDEN_ITEMS_TB_INSERTAR_TG;

COMMIT;


--------------------------------------------------------------
CREATE SEQUENCE ID_FACTURA_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FIDE_FACTURA_TB_INSERTAR_TG
    BEFORE INSERT ON FIDE_FACTURA_TB
    FOR EACH ROW
    BEGIN
        
        SELECT ID_FACTURA_SEQ.NEXTVAL INTO :NEW.ID_FACTURA FROM DUAL;
END FIDE_FACTURA_TB_INSERTAR_TG;

COMMIT;
-----------------------------
-- Crear la secuencia para generar valores automáticos
CREATE SEQUENCE FIDE_PROVEEDORES_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Crear el trigger para asignar el valor a ID_PROVEEDOR automáticamente
CREATE OR REPLACE TRIGGER FIDE_PROVEEDORES_TB_BEFORE_INSERT
BEFORE INSERT ON FIDE_PROVEEDORES_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_PROVEEDOR IS NULL THEN
        SELECT FIDE_PROVEEDORES_SEQ.NEXTVAL
        INTO :NEW.ID_PROVEEDOR
        FROM dual;
    END IF;
END;
/

--CREACION DE SECUENCIA PARA TABLA MEMBRESIAS
CREATE SEQUENCE ID_MEMBRESIA_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FIDE_MEMBRESIAS_TB_INSERTAR_TG
    BEFORE INSERT ON FIDE_MEMBRESIAS_TB
    FOR EACH ROW
    BEGIN
        
        SELECT ID_MEMBRESIA_SEQ.NEXTVAL INTO :NEW.ID_MEMBRESIA FROM DUAL;
END FIDE_MEMBRESIAS_TB_INSERTAR_TG;

COMMIT;

-----TRIGGER PARA VALIDAR SI EL USUARIO YA ESTA REGISTRADO EN EL EVENTO
CREATE OR REPLACE TRIGGER FIDE_REGISTRO_EVENTOS_TB_VALIDAR_REGISTRO_TG
BEFORE INSERT ON FIDE_REGISTRO_EVENTOS_TB
FOR EACH ROW
DECLARE
    V_EXISTE_REGISTRO NUMBER;
BEGIN
    -- Verificar si ya existe un registro con el mismo CEDULA y ID_EVENTO
    SELECT COUNT(*) INTO V_EXISTE_REGISTRO
    FROM FIDE_REGISTRO_EVENTOS_TB
    WHERE CEDULA = :NEW.CEDULA
    AND ID_EVENTO = :NEW.ID_EVENTO;

    -- Si ya existe un registro, lanzar un error
    IF V_EXISTE_REGISTRO > 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'El usuario ya está registrado en este evento.');
    END IF;
END;

COMMIT;