--PROCEDIMIENTOS ALMACENADOS
CREATE OR REPLACE PROCEDURE FIDE_TIPO_MEMBRESIAS_TB_OBTENER_MEMBRESIAS_SP (P_CURSOR OUT SYS_REFCURSOR)
IS
    V_CONTAR NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_CONTAR FROM FIDE_TIPO_MEMBRESIAS_TB WHERE ID_ESTADO = 1;
    IF V_CONTAR> 0 THEN
    OPEN P_CURSOR FOR
    SELECT ID_TIPO_MEMBRESIA, COSTO, DURACION_DIAS, NOMBRE, NUM_INVITADOS, DESCRIPCION
    FROM FIDE_TIPO_MEMBRESIAS_TB
    WHERE ID_ESTADO = 1;
    
    ELSE 
     OPEN p_cursor FOR
        SELECT 'No existen membresías disponibles' AS MENSAJE, NULL AS ID_TIPO_MEMBRESIA, NULL AS COSTO, NULL AS DURACION_DIAS, NULL AS NOMBRE, NULL AS NUM_INVITADOS FROM DUAL;
    END IF;
END;

COMMIT;


INSERT INTO FIDE_ESTADO_TB (ID_ESTADO, DESCRIPCION) VALUES (1, 'ACTIVO');
INSERT INTO FIDE_TIPO_MEMBRESIAS_TB (ID_TIPO_MEMBRESIA, COSTO, NOMBRE, DURACION_DIAS, NUM_INVITADOS, ID_ESTADO, DESCRIPCION)
VALUES (1, 20000.0, 'MEMBERESIA JAULES BÁSICA', 365, 1, 1, 'MEMBRESÍA BÁSICA, CON ACCESO LIMITADO A NUESTRAS INSTALACIONES'); 
COMMIT;

VAR rc REFCURSOR;
BEGIN
    FIDE_TIPO_MEMBRESIAS_TB_OBTENER_MEMBRESIAS_SP(:rc);
    PRINT rc;
END;