INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (1, 32, 1, 3);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (2, 19, 2, 5);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (3, 70, 3, 3);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (4, 86, 4, 18);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (5, 49, 5, 7);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (6, 30, 6, 10);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (7, 73, 7, 10);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (8, 65, 8, 5);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (9, 71, 9, 4);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (10, 52, 10, 13);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (11, 93, 11, 13);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (12, 53, 12, 18);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (13, 15, 13, 5);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (14, 77, 14, 12);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (15, 10, 15, 9);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (16, 59, 16, 14);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (17, 58, 17, 17);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (18, 93, 18, 19);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (19, 18, 19, 11);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (20, 38, 20, 14);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (21, 77, 21, 6);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (22, 68, 22, 16);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (23, 62, 23, 15);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (24, 100, 24, 19);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (25, 81, 25, 13);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (26, 54, 26, 6);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (27, 30, 27, 5);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (28, 81, 28, 19);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (29, 43, 29, 20);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (30, 75, 30, 19);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (31, 49, 31, 12);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (32, 40, 32, 17);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (33, 55, 33, 17);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (34, 93, 34, 8);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (35, 98, 35, 19);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (36, 88, 36, 13);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (37, 90, 37, 18);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (38, 90, 38, 12);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (39, 75, 39, 20);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (40, 25, 40, 6);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (41, 38, 41, 19);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (42, 84, 42, 18);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (43, 71, 43, 6);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (44, 55, 44, 20);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (45, 40, 45, 14);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (46, 44, 46, 11);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (47, 41, 47, 20);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (48, 79, 48, 3);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (49, 31, 49, 14);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (50, 24, 50, 19);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (51, 19, 51, 4);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (52, 82, 52, 17);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (53, 50, 53, 17);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (54, 61, 54, 4);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (55, 99, 55, 15);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (56, 29, 56, 14);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (57, 17, 57, 6);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (58, 71, 58, 14);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (59, 91, 59, 6);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (60, 74, 60, 10);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (61, 82, 61, 18);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (62, 60, 62, 10);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (63, 77, 63, 11);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (64, 21, 64, 6);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (65, 38, 65, 20);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (66, 65, 66, 6);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (67, 78, 67, 11);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (68, 11, 68, 17);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (69, 91, 69, 14);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (70, 21, 70, 10);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (71, 28, 71, 4);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (72, 21, 72, 16);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (73, 65, 73, 7);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (74, 65, 74, 10);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (75, 17, 75, 20);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (76, 28, 76, 13);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (77, 98, 77, 18);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (78, 14, 78, 12);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (79, 80, 79, 5);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (80, 17, 80, 4);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (81, 37, 81, 7);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (82, 69, 82, 18);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (83, 27, 83, 19);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (84, 64, 84, 4);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (85, 51, 85, 11);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (86, 92, 86, 17);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (87, 82, 87, 13);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (88, 66, 88, 3);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (89, 40, 89, 6);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (90, 50, 90, 18);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (91, 73, 91, 10);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (92, 29, 92, 8);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (93, 59, 93, 5);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (94, 13, 94, 18);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (95, 95, 95, 11);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (96, 96, 96, 14);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (97, 52, 97, 19);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (98, 22, 98, 8);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (99, 90, 99, 16);
INSERT INTO FIDE_INVENTARIO_TB 
(ID_INVENTARIO, CANTIDAD, ID_PRODUCTO, CANTIDAD_MINIMA) 
VALUES (100, 93, 100, 4);