--FIDE_BENEFICIOS_TB

INSERT INTO FIDE_BENEFICIOS_TB (ID_BENEFICIO, DESCRIPCION, ID_ESTADO) VALUES (1, 'Acceso a la piscina', 1);
INSERT INTO FIDE_BENEFICIOS_TB (ID_BENEFICIO, DESCRIPCION, ID_ESTADO) VALUES (2, 'Uso de gimnasio', 1);
INSERT INTO FIDE_BENEFICIOS_TB (ID_BENEFICIO, DESCRIPCION, ID_ESTADO) VALUES (3, 'Descuentos en eventos', 0);
INSERT INTO FIDE_BENEFICIOS_TB (ID_BENEFICIO, DESCRIPCION, ID_ESTADO) VALUES (4, 'Acceso a zonas VIP', 1);
INSERT INTO FIDE_BENEFICIOS_TB (ID_BENEFICIO, DESCRIPCION, ID_ESTADO) VALUES (5, 'Estacionamiento exclusivo', 1);
INSERT INTO FIDE_BENEFICIOS_TB (ID_BENEFICIO, DESCRIPCION, ID_ESTADO) VALUES (6, 'Participación en torneos deportivos', 0);
INSERT INTO FIDE_BENEFICIOS_TB (ID_BENEFICIO, DESCRIPCION, ID_ESTADO) VALUES (7, 'Acceso a biblioteca recreativa', 1);
INSERT INTO FIDE_BENEFICIOS_TB (ID_BENEFICIO, DESCRIPCION, ID_ESTADO) VALUES (8, 'Internet inalámbrico gratuito', 1);
INSERT INTO FIDE_BENEFICIOS_TB (ID_BENEFICIO, DESCRIPCION, ID_ESTADO) VALUES (9, 'Alquiler gratuito de equipo deportivo', 0);
INSERT INTO FIDE_BENEFICIOS_TB (ID_BENEFICIO, DESCRIPCION, ID_ESTADO) VALUES (10, 'Talleres gratuitos', 1);
INSERT INTO FIDE_BENEFICIOS_TB (ID_BENEFICIO, DESCRIPCION, ID_ESTADO) VALUES (11, 'Acceso a zona de picnic', 1);
INSERT INTO FIDE_BENEFICIOS_TB (ID_BENEFICIO, DESCRIPCION, ID_ESTADO) VALUES (12, 'Ingreso prioritario a eventos', 1);
INSERT INTO FIDE_BENEFICIOS_TB (ID_BENEFICIO, DESCRIPCION, ID_ESTADO) VALUES (13, 'Acceso a juegos de mesa y salón recreativo', 0);
INSERT INTO FIDE_BENEFICIOS_TB (ID_BENEFICIO, DESCRIPCION, ID_ESTADO) VALUES (14, 'Descuentos en restaurante', 1);
INSERT INTO FIDE_BENEFICIOS_TB (ID_BENEFICIO, DESCRIPCION, ID_ESTADO) VALUES (15, 'Invitados gratis en días especiales', 1);
INSERT INTO FIDE_BENEFICIOS_TB (ID_BENEFICIO, DESCRIPCION, ID_ESTADO) VALUES (16, 'Uso de BBQ ranchos', 1);
INSERT INTO FIDE_BENEFICIOS_TB (ID_BENEFICIO, DESCRIPCION, ID_ESTADO) VALUES (17, 'Acceso a áreas verdes y senderos', 0);
INSERT INTO FIDE_BENEFICIOS_TB (ID_BENEFICIO, DESCRIPCION, ID_ESTADO) VALUES (18, 'Uso de cabañas de descanso', 1);
INSERT INTO FIDE_BENEFICIOS_TB (ID_BENEFICIO, DESCRIPCION, ID_ESTADO) VALUES (19, 'Atención personalizada en recepción', 1);
INSERT INTO FIDE_BENEFICIOS_TB (ID_BENEFICIO, DESCRIPCION, ID_ESTADO) VALUES (20, 'Participación en rifas y sorteos', 1);
