INSERT INTO FIDE_TIPO_MEMBRESIAS_TB (COSTO, DURACION_DIAS, DESCRIPCION, NOMBRE, NUM_INVITADOS, ID_ESTADO) VALUES (2500, 1, 'Acceso por un solo día a las instalaciones del club', 'Pase del Día', 0, 1);
INSERT INTO FIDE_TIPO_MEMBRESIAS_TB (COSTO, DURACION_DIAS, DESCRIPCION, NOMBRE, NUM_INVITADOS, ID_ESTADO) VALUES (25000, 365, 'Membresía mensual con acceso básico a instalaciones', 'Básica', 1, 1);
INSERT INTO FIDE_TIPO_MEMBRESIAS_TB (COSTO, DURACION_DIAS, DESCRIPCION, NOMBRE, NUM_INVITADOS, ID_ESTADO) VALUES (50000, 365, 'Acceso mensual a gimnasio, piscina y eventos fitness', 'Fit', 2, 1);
INSERT INTO FIDE_TIPO_MEMBRESIAS_TB (COSTO, DURACION_DIAS, DESCRIPCION, NOMBRE, NUM_INVITADOS, ID_ESTADO) VALUES (100000, 365, 'Acceso completo a todas las áreas y beneficios VIP', 'Premium', 4, 1);

TRUNCATE TABLE FIDE_ORDENES_TB
TRUNCATE TABLE FIDE_FACTURA_TB
TRUNCATE TABLE FIDE_TIPO_MEMBRESIAS_TB
TRUNCATE TABLE FIDE_MEMBRESIAS_TB

SELECT ID_TIPO_MEMBRESIA_SEQ.NEXTVAL FROM DUAL

DROP SEQUENCE ID_TIPO_MEMBRESIA_SEQ
CREATE SEQUENCE ID_TIPO_MEMBRESIA_SEQ INCREMENT BY 1 START WITH 1
MAXVALUE 999999 MINVALUE 0;

COMMIT;