INSERT INTO FIDE_PROVINCIAS_TB (ID_PROVINCIA, NOMBRE) VALUES (1, 'San José');
INSERT INTO FIDE_PROVINCIAS_TB (ID_PROVINCIA, NOMBRE) VALUES (2, 'Alajuela');
INSERT INTO FIDE_PROVINCIAS_TB (ID_PROVINCIA, NOMBRE) VALUES (3, 'Cartago');
INSERT INTO FIDE_PROVINCIAS_TB (ID_PROVINCIA, NOMBRE) VALUES (4, 'Heredia');
INSERT INTO FIDE_PROVINCIAS_TB (ID_PROVINCIA, NOMBRE) VALUES (5, 'Guanacaste');
INSERT INTO FIDE_PROVINCIAS_TB (ID_PROVINCIA, NOMBRE) VALUES (6, 'Puntarenas');
INSERT INTO FIDE_PROVINCIAS_TB (ID_PROVINCIA, NOMBRE) VALUES (7, 'Limón');
