INSERT INTO FIDE_TIPO_INSTALACION_TB (ID_TIPO_INSTALACION, DESCRIPCION, ID_ESTADO) VALUES (1, 'Deportiva', 1);
INSERT INTO FIDE_TIPO_INSTALACION_TB (ID_TIPO_INSTALACION, DESCRIPCION, ID_ESTADO) VALUES (2, 'Recreativa', 1);
INSERT INTO FIDE_TIPO_INSTALACION_TB (ID_TIPO_INSTALACION, DESCRIPCION, ID_ESTADO) VALUES (3, 'Social', 1);
INSERT INTO FIDE_TIPO_INSTALACION_TB (ID_TIPO_INSTALACION, DESCRIPCION, ID_ESTADO) VALUES (4, 'Educativa', 1);
INSERT INTO FIDE_TIPO_INSTALACION_TB (ID_TIPO_INSTALACION, DESCRIPCION, ID_ESTADO) VALUES (5, 'Mixta', 1);
