INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (1, 18, 1, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (2, 17, 2, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (3, 1, 3, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (4, 3, 4, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (5, 4, 5, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (6, 20, 6, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (7, 15, 7, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (8, 11, 8, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (9, 6, 9, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (10, 18, 10, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (11, 16, 11, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (12, 8, 12, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (13, 17, 13, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (14, 11, 14, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (15, 6, 15, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (16, 2, 16, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (17, 7, 17, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (18, 5, 18, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (19, 12, 19, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (20, 11, 20, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (21, 1, 21, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (22, 3, 22, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (23, 14, 23, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (24, 13, 24, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (25, 8, 25, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (26, 18, 26, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (27, 4, 27, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (28, 1, 28, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (29, 16, 29, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (30, 1, 30, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (31, 17, 31, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (32, 1, 32, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (33, 20, 33, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (34, 3, 34, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (35, 18, 35, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (36, 9, 36, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (37, 3, 37, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (38, 1, 38, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (39, 15, 39, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (40, 16, 40, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (41, 4, 41, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (42, 18, 42, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (43, 18, 43, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (44, 10, 44, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (45, 3, 45, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (46, 13, 46, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (47, 13, 47, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (48, 18, 48, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (49, 13, 49, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (50, 13, 50, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (51, 20, 51, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (52, 16, 52, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (53, 5, 53, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (54, 1, 54, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (55, 17, 55, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (56, 9, 56, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (57, 13, 57, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (58, 6, 58, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (59, 6, 59, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (60, 19, 60, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (61, 20, 61, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (62, 7, 62, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (63, 2, 63, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (64, 18, 64, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (65, 20, 65, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (66, 12, 66, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (67, 6, 67, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (68, 19, 68, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (69, 17, 69, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (70, 16, 70, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (71, 5, 71, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (72, 16, 72, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (73, 1, 73, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (74, 3, 74, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (75, 17, 75, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (76, 9, 76, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (77, 14, 77, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (78, 1, 78, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (79, 14, 79, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (80, 14, 80, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (81, 16, 81, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (82, 1, 82, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (83, 17, 83, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (84, 20, 84, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (85, 19, 85, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (86, 13, 86, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (87, 18, 87, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (88, 10, 88, 1);
INSERT INTO FIDE_PRODUCTOS_PROVEEDOR_TB 
(ID_PROD_PROVEEDOR, ID_PROVEEDOR, ID_PRODUCTO, ID_ESTADO) 
VALUES (89, 4, 89, 1);