INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (1, 0, 'Servicios de Servicio de lavandería', 69306106, 'servicio_de_lavandería1@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (2, 0, 'Servicios de Reparaciones generales', 81639317, 'reparaciones_generales2@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (3, 0, 'Servicios de Pintura de instalaciones', 76719900, 'pintura_de_instalaciones3@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (4, 1, 'Servicios de Fotografía para eventos', 72019838, 'fotografía_para_eventos4@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (5, 1, 'Servicios de CCTV y monitoreo', 73217598, 'cctv_y_monitoreo5@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (6, 1, 'Servicios de Reparaciones generales', 88062422, 'reparaciones_generales6@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (7, 1, 'Servicios de Alquiler de toldos', 82256995, 'alquiler_de_toldos7@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (8, 0, 'Servicios de Mantenimiento de canchas', 70645803, 'mantenimiento_de_canchas8@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (9, 0, 'Servicios de Mantenimiento de cabañas', 63161090, 'mantenimiento_de_cabanas9@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (10, 0, 'Servicios de Servicio de catering', 76498233, 'servicio_de_catering10@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (11, 1, 'Servicios de Limpieza profunda', 63904740, 'limpieza_profunda11@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (12, 0, 'Servicios de Servicio de catering', 66693926, 'servicio_de_catering12@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (13, 1, 'Servicios de Servicio de catering', 84262912, 'servicio_de_catering13@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (14, 0, 'Servicios de Fotografía para eventos', 63742754, 'fotografía_para_eventos14@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (15, 0, 'Servicios de Limpieza profunda', 87756561, 'limpieza_profunda15@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (16, 0, 'Servicios de Mantenimiento de canchas', 61804946, 'mantenimiento_de_canchas16@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (17, 1, 'Servicios de CCTV y monitoreo', 60304560, 'cctv_y_monitoreo17@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (18, 1, 'Servicios de Limpieza de salones', 78991683, 'limpieza_de_salones18@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (19, 1, 'Servicios de Mantenimiento de canchas', 89978976, 'mantenimiento_de_canchas19@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (20, 1, 'Servicios de Pintura de instalaciones', 60241582, 'pintura_de_instalaciones20@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (21, 1, 'Servicios de Internet y redes', 85272454, 'internet_y_redes21@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (22, 0, 'Servicios de Reparaciones generales', 61118036, 'reparaciones_generales22@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (23, 1, 'Servicios de Sonido e iluminación', 75355067, 'sonido_e_iluminación23@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (24, 1, 'Servicios de Mantenimiento de sauna y jacuzzi', 72884477, 'mantenimiento_de_sauna_y_jacuzzi24@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (25, 0, 'Servicios de Servicio de lavandería', 67312942, 'servicio_de_lavandería25@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (26, 0, 'Servicios de Recolección de basura', 72086785, 'recolección_de_basura26@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (27, 0, 'Servicios de Electricidad', 75933480, 'electricidad27@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (28, 0, 'Servicios de Mantenimiento de gimnasios', 86138512, 'mantenimiento_de_gimnasios28@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (29, 1, 'Servicios de Mantenimiento de sauna y jacuzzi', 76087037, 'mantenimiento_de_sauna_y_jacuzzi29@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (30, 0, 'Servicios de CCTV y monitoreo', 79816312, 'cctv_y_monitoreo30@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (31, 0, 'Servicios de Mantenimiento de gimnasios', 89225932, 'mantenimiento_de_gimnasios31@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (32, 0, 'Servicios de Mantenimiento de gimnasios', 64611145, 'mantenimiento_de_gimnasios32@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (33, 0, 'Servicios de Servicio de lavandería', 63525460, 'servicio_de_lavandería33@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (34, 1, 'Servicios de Decoración de eventos', 89042933, 'decoración_de_eventos34@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (35, 0, 'Servicios de Sonido e iluminación', 83061607, 'sonido_e_iluminación35@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (36, 0, 'Servicios de Internet y redes', 62057733, 'internet_y_redes36@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (37, 1, 'Servicios de Fotografía para eventos', 87718407, 'fotografía_para_eventos37@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (38, 0, 'Servicios de Mantenimiento de cabañas', 69997983, 'mantenimiento_de_cabanas38@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (39, 0, 'Servicios de Internet y redes', 71283495, 'internet_y_redes39@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (40, 1, 'Servicios de CCTV y monitoreo', 64270813, 'cctv_y_monitoreo40@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (41, 1, 'Servicios de Limpieza profunda', 79875242, 'limpieza_profunda41@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (42, 1, 'Servicios de Limpieza profunda', 85426009, 'limpieza_profunda42@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (43, 1, 'Servicios de Control de plagas', 83229966, 'control_de_plagas43@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (44, 1, 'Servicios de Limpieza de salones', 84924678, 'limpieza_de_salones44@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (45, 0, 'Servicios de Jardinería', 80106901, 'jardinería45@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (46, 1, 'Servicios de Recolección de basura', 65677183, 'recolección_de_basura46@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (47, 0, 'Servicios de Mantenimiento de gimnasios', 63885986, 'mantenimiento_de_gimnasios47@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (48, 0, 'Servicios de Servicio de lavandería', 75527249, 'servicio_de_lavandería48@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (49, 0, 'Servicios de Fontanería', 60881587, 'fontanería49@clubjaules.com');
INSERT INTO FIDE_PROVEEDORES_TB (ID_PROVEEDOR, ID_ESTADO, NOMBRE, TELEFONO, EMAIL) VALUES (50, 0, 'Servicios de Servicio de catering', 60938594, 'servicio_de_catering50@clubjaules.com');

COMMIT;