--FIDE_CANTONES_TB

--San Jose = 1
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (101, 'San José', 1);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (102, 'Escazú', 1);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (103, 'Desamparados', 1);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (104, 'Puriscal', 1);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (105, 'Tarrazú', 1);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (106, 'Aserrí', 1);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (107, 'Mora', 1);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (108, 'Goicoechea', 1);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (109, 'Santa Ana', 1);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (110, 'Alajuelita', 1);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (111, 'Vázquez de Coronado', 1);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (112, 'Acosta', 1);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (113, 'Tibás', 1);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (114, 'Moravia', 1);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (115, 'Montes de Oca', 1);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (116, 'Turrubares', 1);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (117, 'Dota', 1);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (118, 'Curridabat', 1);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (119, 'Pérez Zeledón', 1);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (120, 'León Cortés Castro', 1);

--Alajuela = 2
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (201, 'Alajuela', 2);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (202, 'San Ramón', 2);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (203, 'Grecia', 2);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (204, 'San Mateo', 2);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (205, 'Atenas', 2);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (206, 'Naranjo', 2);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (207, 'Palmares', 2);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (208, 'Poás', 2);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (209, 'Orotina', 2);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (210, 'San Carlos', 2);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (211, 'Zarcero', 2);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (212, 'Sarchí', 2);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (213, 'Upala', 2);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (214, 'Los Chiles', 2);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (215, 'Guatuso', 2);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (216, 'Río Cuarto', 2);

--Cartago = 3
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (301, 'Cartago', 3);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (302, 'Paraíso', 3);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (303, 'La Unión', 3);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (304, 'Jiménez', 3);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (305, 'Turrialba', 3);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (306, 'Alvarado', 3);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (307, 'Oreamuno', 3);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (308, 'El Guarco', 3);

--Heredia = 4
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (401, 'Heredia', 4);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (402, 'Barva', 4);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (403, 'Santo Domingo', 4);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (404, 'Santa Bárbara', 4);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (405, 'San Rafael', 4);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (406, 'San Isidro', 4);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (407, 'Belén', 4);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (408, 'Flores', 4);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (409, 'San Pablo', 4);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (410, 'Sarapiquí', 4);

--Guanacaste = 5
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (501, 'Liberia', 5);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (502, 'Nicoya', 5);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (503, 'Santa Cruz', 5);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (504, 'Bagaces', 5);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (505, 'Carrillo', 5);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (506, 'Cañas', 5);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (507, 'Abangares', 5);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (508, 'Tilarán', 5);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (509, 'Nandayure', 5);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (510, 'La Cruz', 5);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (511, 'Hojancha', 5);

--Puntarenas = 6
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (601, 'Puntarenas', 6);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (602, 'Esparza', 6);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (603, 'Buenos Aires', 6);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (604, 'Montes de Oro', 6);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (605, 'Osa', 6);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (606, 'Quepos', 6);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (607, 'Golfito', 6);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (608, 'Coto Brus', 6);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (609, 'Parrita', 6);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (610, 'Corredores', 6);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (611, 'Garabito', 6);

--Limon = 7
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (701, 'Limón', 7);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (702, 'Pococí', 7);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (703, 'Siquirres', 7);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (704, 'Talamanca', 7);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (705, 'Matina', 7);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE, ID_PROVINCIA) VALUES (706, 'Guácimo', 7);