--Tabla FIDE_DISTRITOS_TB

--HEREDIA
--Heredia 
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (1, 'Heredia', 401);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (2, 'Mercedes', 401);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (3, 'San Francisco', 401);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (4, 'Ulloa', 401);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (5, 'Vara Blanca', 401);

--Barva 
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (6, 'Barva', 402);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (7, 'San Pedro', 402);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (8, 'San Pablo', 402);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (9, 'San Roque', 402);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (10, 'Santa Lucía', 402);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (11, 'San José de la Montaña', 402);

--Santo Domingo 
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (12, 'Santo Domingo', 403);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (13, 'San Vicente', 403);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (14, 'San Miguel', 403);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (15, 'Paracito', 403);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (16, 'Santo Tomás', 403);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (17, 'Santa Rosa', 403);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (18, 'Tures', 403);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (19, 'Pará', 403);

--Santa Bárbara 
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (20, 'Santa Bárbara', 404);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (21, 'San Pedro', 404);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (22, 'San Juan', 404);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (23, 'Jesús', 404);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (24, 'Santo Domingo', 404);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (25, 'Purabá', 404);

--San Rafael 
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (26, 'San Rafael', 405);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (27, 'San Josecito', 405);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (28, 'Santiago', 405);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (29, 'Los Ángeles', 405);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (30, 'Concepción', 405);

 --San Isidro 
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (31, 'San Isidro', 406);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (32, 'San José', 406);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (33, 'Concepción', 406);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (34, 'San Francisco', 406);

-- Belén 
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (1, 'San Antonio', 407);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (2, 'La Ribera', 407);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (3, 'La Asunción', 407);

--Flores 
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (4, 'San Joaquín', 408);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (5, 'Barrantes', 408);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (6, 'Llorente', 408);

--San Pablo 
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (7, 'San Pablo', 409);

--Sarapiquí 
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (8, 'Puerto Viejo', 410);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (9, 'La Virgen', 410);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (10, 'Horquetas', 410);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (11, 'Llanuras del Gaspar', 410);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (12, 'Cureña', 410);


--CARTAGO

-- Cartago 
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (1, 'Oriental', 301);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (2, 'Occidental', 301);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (3, 'Carmen', 301);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (4, 'San Nicolás', 301);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (5, 'Aguacaliente', 301);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (6, 'Guadalupe', 301);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (7, 'Corralillo', 301);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (8, 'Tierra Blanca', 301);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (9, 'Dulce Nombre', 301);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (10, 'Llano Grande', 301);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (11, 'Quebradilla', 301);

--Paraíso 
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (12, 'Paraíso', 302);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (13, 'Santiago', 302);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (14, 'Orosi', 302);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (15, 'Cachí', 302);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (16, 'Llanos de Santa Lucía', 302);

--La Unión 
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (17, 'Tres Ríos', 303);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (18, 'San Diego', 303);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (19, 'San Juan', 303);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (20, 'San Rafael', 303);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (21, 'Concepción', 303);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (22, 'Dulce Nombre', 303);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (23, 'San Ramón', 303);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (24, 'Río Azul', 303);

-- Jiménez 
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (25, 'Juan Viñas', 304);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (26, 'Tucurrique', 304);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (27, 'Pejibaye', 304);

-- Turrialba 
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (28, 'Turrialba', 305);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (29, 'La Suiza', 305);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (30, 'Peralta', 305);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (31, 'Santa Cruz', 305);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (32, 'Santa Teresita', 305);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (33, 'Pavones', 305);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (34, 'Tuis', 305);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (35, 'Tayutic', 305);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (36, 'Santa Rosa', 305);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (37, 'Tres Equis', 305);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (38, 'La Isabel', 305);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (39, 'Chirripó', 305);

--Alvarado
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (40, 'Pacayas', 306);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (41, 'Cervantes', 306);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (42, 'Capellades', 306);

--Oreamundo
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (43, 'San Rafael', 307);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (44, 'Cot', 307);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (45, 'Potrero Cerrado', 307);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (46, 'Cipreses', 307);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (47, 'Santa Rosa', 307);

--El Guarco
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (48, 'Tejar', 308);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (49, 'San Isidro', 308);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (50, 'Tobosi', 308);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (51, 'Patio de Agua', 308);

--Guanacaste--

--Liberia
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (1, 'Liberia', 501);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (2, 'Cañas Dulces', 501);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (3, 'Mayorga', 501);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (4, 'Nacascolo', 501);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (5, 'Curubandé', 501);


--Nicoya
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (6, 'Nicoya', 502);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (7, 'Mansión', 502);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (8, 'San Antonio', 502);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (9, 'Quebrada Honda', 502);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (10, 'Sámara', 502);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (11, 'Nosara', 502);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (12, 'Belén de Nosarita', 502);

--Santa Cruz
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (13, 'Santa Cruz', 503);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (14, 'Bolsón', 503);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (15, 'Veintisiete de Abril', 503);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (16, 'Tempate', 503);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (17, 'Cartagena', 503);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (18, 'Cuajiniquil', 503);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (19, 'Diriá', 503);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (20, 'Cabo Velas', 503);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (21, 'Tamarindo', 503);

--Bagaces
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (22, 'Bagaces', 504);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (23, 'La Fortuna', 504);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (24, 'Mogote', 504);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (25, 'Río Naranjo', 504);

--Carrillo
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (35, 'Filadelfia', 505);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (36, 'Palmira', 505);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (37, 'Sardinal', 505);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (38, 'Belén', 505);

--Cañas
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (26, 'Cañas', 506);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (27, 'Palmira', 506);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (28, 'San Miguel', 506);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (29, 'Bebedero', 506);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (30, 'Porozal', 506);


--Abangares
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (31, 'Las Juntas', 507);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (32, 'Sierra', 507);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (33, 'San Juan', 507);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (34, 'Colorado', 507);

--Tilaran
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (61, 'Tilarán', 508);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (62, 'Quebrada Grande', 508);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (63, 'Tronadora', 508);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (64, 'Santa Rosa', 508);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (65, 'Líbano', 508);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (66, 'Tierras Morenas', 508);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (67, 'Arenal', 508);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (68, 'Cabeceras', 508);


--Nandayure
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (47, 'Carmona', 509);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (48, 'Santa Rita', 509);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (49, 'Zapotal', 509);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (50, 'San Pablo', 509);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (51, 'Porvenir', 509);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (52, 'Bejuco', 509);


--La Cruz
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (53, 'La Cruz', 510);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (54, 'Santa Cecilia', 510);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (55, 'La Garita', 510);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (56, 'Santa Elena', 510);

--Hojancha
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (57, 'Hojancha', 511);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (58, 'Monte Romo', 511);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (59, 'Puerto Carrillo', 511);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (60, 'Huacas', 511);


--Limon--

--Limon
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (69, 'Limón', 701);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (70, 'Valle La Estrella', 701);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (71, 'Río Blanco', 701);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (72, 'Matama', 701);


--Pococi
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (73, 'Guápiles', 702);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (74, 'Jiménez', 702);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (75, 'La Rita', 702);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (76, 'Roxana', 702);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (77, 'Cariari', 702);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (78, 'Colorado', 702);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (79, 'La Colonia', 702);


--Siquirres
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (80, 'Siquirres', 703);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (81, 'Pacuarito', 703);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (82, 'Florida', 703);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (83, 'Germania', 703);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (84, 'Cairo', 703);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (85, 'Alegría', 703);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (86, 'Reventazón', 703);


--Talamanca
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (87, 'Bratsi', 704);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (88, 'Sixaola', 704);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (89, 'Cahuita', 704);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (90, 'Telire', 704);


--Matina
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (91, 'Matina', 705);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (92, 'Batán', 705);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (93, 'Carrandí', 705);


--Guacimo
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (94, 'Guácimo', 706);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (95, 'Mercedes', 706);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (96, 'Pocora', 706);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (97, 'Río Jiménez', 706);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (98, 'Duacarí', 706);


--Puntarenas--

--Puntarenas
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (99, 'Puntarenas', 601);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (100, 'Pitahaya', 601);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (101, 'Chomes', 601);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (102, 'Lepanto', 601);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (103, 'Paquera', 601);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (104, 'Manzanillo', 601);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (105, 'Guacimal', 601);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (106, 'Barranca', 601);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (107, 'Isla del Coco', 601);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (108, 'Cóbano', 601);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (109, 'Chacarita', 601);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (110, 'Chira', 601);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (111, 'Acapulco', 601);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (112, 'El Roble', 601);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (113, 'Arancibia', 601);


--Esparza
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (114, 'Espíritu Santo', 602);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (115, 'San Juan Grande', 602);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (116, 'Macacona', 602);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (117, 'San Rafael', 602);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (118, 'San Jerónimo', 602);

--Buenos Aires
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (119, 'Buenos Aires', 603);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (120, 'Volcán', 603);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (121, 'Potrero Grande', 603);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (122, 'Boruca', 603);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (123, 'Pilas', 603);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (124, 'Colinas', 603);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (125, 'Chánguena', 603);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (126, 'Biolley', 603);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (127, 'Brunka', 603);

--Montes de Oro
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (128, 'Miramar', 604);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (129, 'La Unión', 604);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (130, 'San Isidro', 604);

--Osa
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (131, 'Puerto Cortés', 605);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (132, 'Palmar', 605);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (133, 'Sierpe', 605);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (134, 'Bahía Ballena', 605);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (135, 'Piedras Blancas', 605);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (136, 'Bahía Drake', 605);

--Quepos
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (137, 'Quepos', 606);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (138, 'Savegre', 606);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (139, 'Naranjito', 606);

--Golfito
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (140, 'Golfito', 607);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (141, 'Puerto Jiménez', 607);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (142, 'Guaycará', 607);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (143, 'Pavón', 607);

--Coto Brus
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (144, 'San Vito', 608);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (145, 'Sabalito', 608);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (146, 'Aguabuena', 608);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (147, 'Limoncito', 608);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (148, 'Pittier', 608);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (149, 'Gutiérrez Braun', 608);

--Parrita
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (150, 'Parrita', 609);

--Corredores
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (151, 'Corredor', 610);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (152, 'La Cuesta', 610);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (153, 'Canoas', 610);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (154, 'Laurel', 610);

--Garabito
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (155, 'Jacó', 611);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (156, 'Tárcoles', 611);


--ALAJUELA

--Alajuela
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (1, 'Alajuela', 201);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (2, 'San José', 201);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (3, 'Carrizal', 201);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (4, 'San Antonio', 201);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (5, 'Guácima', 201);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (6, 'San Isidro', 201);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (7, 'Sabanilla', 201);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (8, 'San Rafael', 201);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (9, 'Río Segundo', 201);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (10, 'Desamparados', 201);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (11, 'Turrúcares', 201);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (12, 'Tambor', 201);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (13, 'La Garita', 201);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (14, 'Sarapiquí', 201);

--San Ramon
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (15, 'San Ramón', 202);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (16, 'Santiago', 202);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (17, 'San Juan', 202);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (18, 'Piedades Norte', 202);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (19, 'Piedades Sur', 202);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (20, 'San Rafael', 202);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (21, 'San Isidro', 202);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (22, 'Ángeles', 202);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (23, 'Alfaro', 202);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (24, 'Volio', 202);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (25, 'Concepción', 202);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (26, 'Zapotal', 202);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (27, 'Peñas Blancas', 202);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (28, 'San Lorenzo', 202);

--Grecia
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (29, 'Grecia', 203);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (30, 'San Isidro', 203);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (31, 'San José', 203);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (32, 'San Roque', 203);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (33, 'Tacares', 203);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (34, 'Puente de Piedra', 203);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (35, 'Bolívar', 203);

--San Mateo
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (36, 'San Mateo', 204);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (37, 'Desmonte', 204);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (38, 'Jesús María', 204);

--Atenas
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (39, 'Atenas', 205);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (40, 'Jesús', 205);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (41, 'Mercedes', 205);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (42, 'San Isidro', 205);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (43, 'Concepción', 205);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (44, 'San José', 205);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (45, 'Santa Eulalia', 205);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (46, 'Escobal', 205);

--Naranjo
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (47, 'Naranjo', 206);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (48, 'San Miguel', 206);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (49, 'San José', 206);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (50, 'Cirrí Sur', 206);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (51, 'San Jerónimo', 206);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (52, 'San Juan', 206);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (53, 'El Rosario', 206);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (54, 'Palmitos', 206);

--Palmares
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (55, 'Palmares', 207);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (56, 'Zaragoza', 207);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (57, 'Buenos Aires', 207);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (58, 'Santiago', 207);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (59, 'Candelaria', 207);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (60, 'Esquipulas', 207);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (61, 'La Granja', 207);

--Poas
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (62, 'San Pedro', 208);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (63, 'San Juan', 208);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (64, 'San Rafael', 208);

--Orotina
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (65, 'Orotina', 209);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (66, 'El Mastate', 209);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (67, 'Hacienda Vieja', 209);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (68, 'Coyolar', 209);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (69, 'La Ceiba', 209);

--San Carlos
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (70, 'Quesada', 210);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (71, 'Florencia', 210);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (72, 'Buenavista', 210);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (73, 'Aguas Zarcas', 210);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (74, 'Venecia', 210);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (75, 'Pital', 210);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (76, 'La Fortuna', 210);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (77, 'La Tigra', 210);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (78, 'La Palmera', 210);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (79, 'Venado', 210);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (80, 'Cutris', 210);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (81, 'Monterrey', 210);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (82, 'Pocosol', 210);

--Zarcero
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (83, 'Zarcero', 211);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (84, 'Laguna', 211);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (85, 'Tapesco', 211);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (86, 'Guadalupe', 211);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (87, 'Palmira', 211);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (88, 'Zapote', 211);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (89, 'Brisas', 211);

--Sarchi
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (90, 'Sarchí Norte', 212);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (91, 'Sarchí Sur', 212);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (92, 'Toro Amarillo', 212);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (93, 'San Pedro', 212);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (94, 'Rodríguez', 212);

--Upala
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (95, 'Upala', 213);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (96, 'Aguas Claras', 213);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (97, 'San José', 213);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (98, 'Bijagua', 213);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (99, 'Delicias', 213);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (100, 'Dos Ríos', 213);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (101, 'Yolillal', 213);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (102, 'Canalete', 213);

--Los chiles
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (103, 'Los Chiles', 214);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (104, 'Caño Negro', 214);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (105, 'El Amparo', 214);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (106, 'San Jorge', 214);

--Guatuso
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (107, 'San Rafael', 215);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (108, 'Buenavista', 215);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (109, 'Cote', 215);

--Rio cuarto
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (110, 'Río Cuarto', 216);


--SAN JOSE

--San Jose
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (111, 'Carmen', 101);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (112, 'Merced', 101);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (113, 'Hospital', 101);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (114, 'Catedral', 101);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (115, 'Zapote', 101);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (116, 'San Francisco de Dos Ríos', 101);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (117, 'Uruca', 101);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (118, 'Mata Redonda', 101);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (119, 'Pavas', 101);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (120, 'Hatillo', 101);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (121, 'San Sebastián', 101);

--Escazu
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (122, 'Escazú', 102);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (123, 'San Antonio', 102);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (124, 'San Rafael', 102);

--Desamparados
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (125, 'Desamparados', 103);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (126, 'San Miguel', 103);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (127, 'San Juan de Dios', 103);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (128, 'San Rafael Arriba', 103);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (129, 'San Rafael Abajo', 103);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (130, 'San Antonio', 103);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (131, 'Frailes', 103);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (132, 'Patarrá', 103);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (133, 'San Cristóbal', 103);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (134, 'Rosario', 103);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (135, 'Damas', 103);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (136, 'San Jerónimo', 103);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (137, 'Gravilias', 103);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (138, 'Los Guido', 103);

--Puriscal
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (139, 'Santiago', 104);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (140, 'Mercedes Sur', 104);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (141, 'Barbacoas', 104);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (142, 'Grifo Alto', 104);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (143, 'San Rafael', 104);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (144, 'Candelarita', 104);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (145, 'Desamparaditos', 104);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (146, 'San Antonio', 104);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (147, 'Chires', 104);

--Tarrazu
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (148, 'San Marcos', 105);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (149, 'San Lorenzo', 105);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (150, 'San Carlos', 105);

--Asserri
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (151, 'Aserrí', 106);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (152, 'Tarbaca', 106);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (153, 'Vuelta de Jorco', 106);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (154, 'San Gabriel', 106);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (155, 'Legua', 106);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (156, 'Monterrey', 106);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (157, 'Salitrillos', 106);

--Mora
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (158, 'Colón', 107);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (159, 'Guayabo', 107);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (160, 'Tabarcia', 107);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (161, 'Piedras Negras', 107);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (162, 'Picagres', 107);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (163, 'Jaris', 107);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (164, 'Quitirrisí', 107);

--Goicochea
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (165, 'Guadalupe', 108);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (166, 'San Francisco', 108);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (167, 'Calle Blancos', 108);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (168, 'Mata de Plátano', 108);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (169, 'Ipís', 108);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (170, 'Rancho Redondo', 108);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (171, 'Purral', 108);

--Santa Ana
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (172, 'Santa Ana', 109);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (173, 'Salitral', 109);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (174, 'Pozos', 109);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (175, 'Uruca', 109);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (176, 'Piedades', 109);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (177, 'Brasil', 109);

--Alajuelita
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (178, 'Alajuelita', 110);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (179, 'San Josecito', 110);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (180, 'San Antonio', 110);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (181, 'Concepción', 110);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (182, 'San Felipe', 110);

--Vasquez de Coronado
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (183, 'San Isidro', 111);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (184, 'San Rafael', 111);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (185, 'Dulce Nombre de Jesús', 111);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (186, 'Patalillo', 111);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (187, 'Cascajal', 111);

--Acosta
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (188, 'San Ignacio', 112);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (189, 'Guaitil', 112);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (190, 'Palmichal', 112);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (191, 'Cangrejal', 112);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (192, 'Sabanillas', 112);

--Tibas
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (193, 'San Juan', 113);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (194, 'Cinco Esquinas', 113);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (195, 'Anselmo Llorente', 113);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (196, 'León XIII', 113);

--Moravia
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (197, 'San Vicente', 114);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (198, 'San Jerónimo', 114);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (199, 'La Trinidad', 114);

--Montes de Oca
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (200, 'San Pedro', 115);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (201, 'Sabanilla', 115);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (202, 'Mercedes', 115);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (203, 'San Rafael', 115);

--Turrubares
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (204, 'San Pablo', 116);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (205, 'San Pedro', 116);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (206, 'San Juan de Mata', 116);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (207, 'San Luis', 116);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (208, 'Carara', 116);

--Dota
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (209, 'Santa María', 117);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (210, 'Jardín', 117);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (211, 'Copey', 117);

--Curridabat
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (212, 'Curridabat', 118);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (213, 'Granadilla', 118);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (214, 'Sánchez', 118);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (215, 'Tirrases', 118);

--Perez Zeledon
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (216, 'San Isidro de El General', 119);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (217, 'El General', 119);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (218, 'Daniel Flores', 119);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (219, 'Rivas', 119);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (220, 'San Pedro', 119);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (221, 'Platanares', 119);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (222, 'Pejibaye', 119);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (223, 'Cajón', 119);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (224, 'Barú', 119);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (225, 'Río Nuevo', 119);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (226, 'Páramo', 119);

--Leon cortes
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (227, 'San Pablo', 120);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (228, 'San Andrés', 120);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (229, 'Llano Bonito', 120);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (230, 'San Isidro', 120);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (231, 'Santa Cruz', 120);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE, ID_CANTON) VALUES (232, 'San Antonio', 120);


