--PASE DEL DIA
-- Acceso a la piscina
INSERT INTO ADMINISTRATOR.FIDE_BENEFICIOS_MEMBRESIAS_TB (ID_BENEFICIO_MEMBRESIAS, ID_TIPO_MEMB, ID_BENEFICIO, ID_ESTADO)
VALUES (1, 1, 1, 1);

-- Uso de gimnasio
INSERT INTO ADMINISTRATOR.FIDE_BENEFICIOS_MEMBRESIAS_TB (ID_BENEFICIO_MEMBRESIAS, ID_TIPO_MEMB, ID_BENEFICIO, ID_ESTADO)
VALUES (2, 1, 2, 1);

-- Acceso a zonas VIP
INSERT INTO ADMINISTRATOR.FIDE_BENEFICIOS_MEMBRESIAS_TB (ID_BENEFICIO_MEMBRESIAS, ID_TIPO_MEMB, ID_BENEFICIO, ID_ESTADO)
VALUES (3, 1, 4, 1);

--BASICA
-- Acceso a la piscina
INSERT INTO ADMINISTRATOR.FIDE_BENEFICIOS_MEMBRESIAS_TB 
(ID_BENEFICIO_MEMBRESIAS, ID_TIPO_MEMB, ID_BENEFICIO, ID_ESTADO)
VALUES (4, 2, 1, 1);

-- Uso de gimnasio
INSERT INTO ADMINISTRATOR.FIDE_BENEFICIOS_MEMBRESIAS_TB 
(ID_BENEFICIO_MEMBRESIAS, ID_TIPO_MEMB, ID_BENEFICIO, ID_ESTADO)
VALUES (5, 2, 2, 1);

-- Estacionamiento exclusivo
INSERT INTO ADMINISTRATOR.FIDE_BENEFICIOS_MEMBRESIAS_TB 
(ID_BENEFICIO_MEMBRESIAS, ID_TIPO_MEMB, ID_BENEFICIO, ID_ESTADO)
VALUES (6, 2, 5, 1);

-- Acceso a biblioteca recreativa
INSERT INTO ADMINISTRATOR.FIDE_BENEFICIOS_MEMBRESIAS_TB 
(ID_BENEFICIO_MEMBRESIAS, ID_TIPO_MEMB, ID_BENEFICIO, ID_ESTADO)
VALUES (7, 2, 7, 1);


--FIT
-- Acceso a la piscina
INSERT INTO ADMINISTRATOR.FIDE_BENEFICIOS_MEMBRESIAS_TB 
(ID_BENEFICIO_MEMBRESIAS, ID_TIPO_MEMB, ID_BENEFICIO, ID_ESTADO)
VALUES (8, 3, 1, 1);

-- Uso de gimnasio
INSERT INTO ADMINISTRATOR.FIDE_BENEFICIOS_MEMBRESIAS_TB 
(ID_BENEFICIO_MEMBRESIAS, ID_TIPO_MEMB, ID_BENEFICIO, ID_ESTADO)
VALUES (9, 3, 2, 1);

-- Acceso a zonas VIP
INSERT INTO ADMINISTRATOR.FIDE_BENEFICIOS_MEMBRESIAS_TB 
(ID_BENEFICIO_MEMBRESIAS, ID_TIPO_MEMB, ID_BENEFICIO, ID_ESTADO)
VALUES (10, 3, 4, 1);

-- Estacionamiento exclusivo
INSERT INTO ADMINISTRATOR.FIDE_BENEFICIOS_MEMBRESIAS_TB 
(ID_BENEFICIO_MEMBRESIAS, ID_TIPO_MEMB, ID_BENEFICIO, ID_ESTADO)
VALUES (11, 3, 5, 1);

-- Acceso a biblioteca recreativa
INSERT INTO ADMINISTRATOR.FIDE_BENEFICIOS_MEMBRESIAS_TB 
(ID_BENEFICIO_MEMBRESIAS, ID_TIPO_MEMB, ID_BENEFICIO, ID_ESTADO)
VALUES (12, 3, 7, 1);

-- Internet inalámbrico gratuito
INSERT INTO ADMINISTRATOR.FIDE_BENEFICIOS_MEMBRESIAS_TB 
(ID_BENEFICIO_MEMBRESIAS, ID_TIPO_MEMB, ID_BENEFICIO, ID_ESTADO)
VALUES (13, 3, 8, 1);


--PREMIUM
-- Acceso a la piscina
INSERT INTO ADMINISTRATOR.FIDE_BENEFICIOS_MEMBRESIAS_TB 
  (ID_BENEFICIO_MEMBRESIAS, ID_TIPO_MEMB, ID_BENEFICIO, ID_ESTADO)
VALUES 
  (14, 4, 1, 1);

-- Uso de gimnasio
INSERT INTO ADMINISTRATOR.FIDE_BENEFICIOS_MEMBRESIAS_TB 
  (ID_BENEFICIO_MEMBRESIAS, ID_TIPO_MEMB, ID_BENEFICIO, ID_ESTADO)
VALUES 
  (15, 4, 2, 1);

-- Acceso a zonas VIP
INSERT INTO ADMINISTRATOR.FIDE_BENEFICIOS_MEMBRESIAS_TB 
  (ID_BENEFICIO_MEMBRESIAS, ID_TIPO_MEMB, ID_BENEFICIO, ID_ESTADO)
VALUES 
  (16, 4, 4, 1);

-- Estacionamiento exclusivo
INSERT INTO ADMINISTRATOR.FIDE_BENEFICIOS_MEMBRESIAS_TB 
  (ID_BENEFICIO_MEMBRESIAS, ID_TIPO_MEMB, ID_BENEFICIO, ID_ESTADO)
VALUES 
  (17, 4, 5, 1);

-- Acceso a biblioteca recreativa
INSERT INTO ADMINISTRATOR.FIDE_BENEFICIOS_MEMBRESIAS_TB 
  (ID_BENEFICIO_MEMBRESIAS, ID_TIPO_MEMB, ID_BENEFICIO, ID_ESTADO)
VALUES 
  (18, 4, 7, 1);

-- Internet inalámbrico gratuito
INSERT INTO ADMINISTRATOR.FIDE_BENEFICIOS_MEMBRESIAS_TB 
  (ID_BENEFICIO_MEMBRESIAS, ID_TIPO_MEMB, ID_BENEFICIO, ID_ESTADO)
VALUES 
  (19, 4, 8, 1);

-- Talleres gratuitos
INSERT INTO ADMINISTRATOR.FIDE_BENEFICIOS_MEMBRESIAS_TB 
  (ID_BENEFICIO_MEMBRESIAS, ID_TIPO_MEMB, ID_BENEFICIO, ID_ESTADO)
VALUES 
  (20, 4, 10, 1);

-- Acceso a zona de picnic
INSERT INTO ADMINISTRATOR.FIDE_BENEFICIOS_MEMBRESIAS_TB 
  (ID_BENEFICIO_MEMBRESIAS, ID_TIPO_MEMB, ID_BENEFICIO, ID_ESTADO)
VALUES 
  (21, 4, 11, 1);

-- Ingreso prioritario a eventos
INSERT INTO ADMINISTRATOR.FIDE_BENEFICIOS_MEMBRESIAS_TB 
  (ID_BENEFICIO_MEMBRESIAS, ID_TIPO_MEMB, ID_BENEFICIO, ID_ESTADO)
VALUES 
  (22, 4, 12, 1);

-- Descuentos en restaurante
INSERT INTO ADMINISTRATOR.FIDE_BENEFICIOS_MEMBRESIAS_TB 
  (ID_BENEFICIO_MEMBRESIAS, ID_TIPO_MEMB, ID_BENEFICIO, ID_ESTADO)
VALUES 
  (23, 4, 14, 1);

-- Invitados gratis en días especiales
INSERT INTO ADMINISTRATOR.FIDE_BENEFICIOS_MEMBRESIAS_TB 
  (ID_BENEFICIO_MEMBRESIAS, ID_TIPO_MEMB, ID_BENEFICIO, ID_ESTADO)
VALUES 
  (24, 4, 15, 1);

-- Uso de BBQ ranchos
INSERT INTO ADMINISTRATOR.FIDE_BENEFICIOS_MEMBRESIAS_TB 
  (ID_BENEFICIO_MEMBRESIAS, ID_TIPO_MEMB, ID_BENEFICIO, ID_ESTADO)
VALUES 
  (25, 4, 16, 1);

-- Uso de cabañas de descanso
INSERT INTO ADMINISTRATOR.FIDE_BENEFICIOS_MEMBRESIAS_TB 
  (ID_BENEFICIO_MEMBRESIAS, ID_TIPO_MEMB, ID_BENEFICIO, ID_ESTADO)
VALUES 
  (26, 4, 18, 1);

-- Atención personalizada en recepción
INSERT INTO ADMINISTRATOR.FIDE_BENEFICIOS_MEMBRESIAS_TB 
  (ID_BENEFICIO_MEMBRESIAS, ID_TIPO_MEMB, ID_BENEFICIO, ID_ESTADO)
VALUES 
  (27, 4, 19, 1);

-- Participación en rifas y sorteos
INSERT INTO ADMINISTRATOR.FIDE_BENEFICIOS_MEMBRESIAS_TB 
  (ID_BENEFICIO_MEMBRESIAS, ID_TIPO_MEMB, ID_BENEFICIO, ID_ESTADO)
VALUES 
  (28, 4, 20, 1);
